### ISSUE TITLE
Maintain own config through updates

### ISSUE THREAD

**Issue by captainepoch** [LazyVim/LazyVim#1105]
Hello!

I saw LazyVim while looking for stuff for Neovim, and the project is awesome!

I got a question, though. I saw that the user has the ability to add or remove their custom settings (`options.lua`), but the file itself is added into the repository, not ignored. So my question would be: how can we add our own configuration while keeping LazyVim files updated? Not only plugins, but the configuration itself that may change over time.

Thank you!

**Comment by dvic** [comment]
Are you using https://github.com/LazyVim/starter?

**Comment by captainepoch** [comment]
No, I am not. But even if I was using it, it's the same issue.

**Comment by dvic** [comment]
Yes but with that repo as a starter the idea is that you version your config yourself with git and lazyvim is loaded using the lazy.nvim package manager. See https://www.lazyvim.org/installation

**Comment by folke** [comment]
As @dvic mentioned, you are not supposed to fork/clone this repo. Use the starter, or manually add LazyVim to an existing lazy.nvim installation.

Best to just follow the install instructions and clone the starter repo. You do not need to follow updates to that repo, since that does not actually contain any LazyVim code.

**Comment by captainepoch** [comment]
Oh, I didn't understand the `starter` repo correctly. My bad, I apologize for the noise.

Thank you both for your help!
