### ISSUE TITLE
How to configure or disable some of the defaults

### ISSUE THREAD

**Issue by felixendres** [LazyVim/LazyVim#1238]
Hi,

I'm new to neovim (not to vim though) and have installed Lazyvim to quickly get a great and beautiful config for python development. I watched some videos about how to install and configure neovim in general and LazyVim in particular. I've read the [documentation](https://www.lazyvim.org). I tinkered with the things I saw there and also looked through the default config in ~/.local/share/nvim/lazy/LazyVim/..., I also looked into the plugins listed by lazy.

I still cannot find out how to reconfigure and disable default things, so I hope I can find help here.
- Where can I configure the command mode prompt? I need to move it to the center or the bottom of the screen 
- Where can I change the animation for indent scopes? I tried using "_require('mini.indentscope').gen_animation.none()_" in init.lua, like :help mini.indentscope says, but to no avail. 
- Where can I configure the Python LSP?
  - I want to disable ruff and pycodestyles warnings (they default to 79/88 characters line length, in my job we use 120) and use flake8 instead.
  - More importantly: Disable autoformatting on save, as that drowns my functional changes on an existing codebase in formatting changes

I'm sorry if this is obvious, or documented somewhere obvious. I already spent more time trying to figure this out than I am comfortable with. I hope this is the right place to ask.

**Comment by folke** [comment]
You need to read a plugin's documentation as well to see what options are available and how to set them

Also make sure to read the docs for lazy.nvim which is the plugin manager used by LazyVim.

Next time, please use the github discussion for user questions.

Everything you need to know is in the docs.

**Comment by felixendres** [comment]
Thank you for your answer, even if it is RTFM, when I RTFM'd for hours.

**Comment by folke** [comment]
what do you expect? I'm not going to provide support for every plugin used in LazyVim? I have better things to do, sorry.

If you want to learn to properly use Neovim, you will have to read lots and lots of documentation.

**Comment by felixendres** [comment]
My expectation was, that with LazyVim it is easy to customize the config and that it is easier than starting from scratch or using a pre-made distro. That's what the Readme.md states.

I assumed neovim beginners to be in the target group of your project (which is not your fault, it nowhere says so), but given your answer it is now clear that this is not the case. So I am disappointed that "easy to customize"  means "easy only if you already are familiar with neovim + plugins and their configuration in general and lazy.nvim in particular". It's fine if you have better things to do, me too.

**Comment by dpetka2001** [comment]
There is no "easy to customize" without understanding what you're doing, and the only way to achieve that is by reading the docs like it or not. In general if you want to use Neovim efficiently, you will have to read the docs, otherwise maybe this editor is not for you.

**Comment by dpetka2001** [comment]
If you have a problem with a particular plugin, it would be easier to make an issue at that repo, since the maintainer who wrote it will be able to answer you. 
- command prompt: this is done by `noice.nvim`, so you would have to look up there for customization. There is a recipe to move it like normal `cmdline` and there are some issues or discussions (i don't remember exactly) to move it to bottom of screen.
- ruff and pycodestyles: `null-ls` is responsible for that, so you would have to disable `diagnostics.ruff` and enable `diagnostics.flake8`
- autoformat on save: there is actually a keybinding for this, namely `<leader>uf`. Or you can pass `autoformat = false` to `nvim-lspconfig` and then enable it with the same keybinding whenever you want.
- I can't help you with `mini.identscope` since I don't use it that much, so an issue at that repo might provide you with better support.

These are all different plugins than the scope of Lazyvim and naturally you have to read their docs and issues as well in case they provide an answer for your questions.

**Comment by felixendres** [comment]
Thank you @dpetka2001
