### ISSUE TITLE
I'm on vacation till end of September 🏄‍♂️

### ISSUE THREAD

**Issue by folke** [LazyVim/LazyVim#1268]
I'm on vacation till the end of August.

I won't be checking GitHub and won't bring my laptop. See you all soon!

**Comment by NeckBeardPrince** [comment]
As an American, I could really get behind a month-long vacation.

**Comment by Thomashighbaugh** [comment]
Enjoy your vacation, rest well and enjoy your period of refreshment and recuperation! 

@NeckBeardPrince My fellow American, while we might not be able to walk away from our jobs for such an extended holiday (but between jobs, this is possible if you are wise with your finances and luckier than I have ever been), you should detoxify yourself from other work-like commitments (like open source contributions where you are central rockstar dev of a really popular NeoVim package manager and template configuration, which doesn't pay you a dime and there are lots of needy people making constant demands of you) to stave off burn out, substance abuse or other forms of strained mental health even if you continue to work 9-5 5 days a week at your regular job. If you don't you then to do things like suddenly archive some critical project because you can't take it anymore, ghost the community leaving the project in an uncertain limbo moving forward or other regrettable condition. So if anything, maybe that month of vacation, at least from somethings you do, is just what the doctor needed for you too 😁 

Hope everyone stay well and out of the summer heat, unless that's what you like of course!

**Comment by appelgriebsch** [comment]
Hope you had a nice vacation..... and I guess this can be closed? @folke
