### ISSUE TITLE
No completions for Tailwind CSS Extra when editing HTML

### ISSUE THREAD

**Issue by scottmckendry** [LazyVim/LazyVim#1317]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.1

### Operating system/version

W11 22H2

### Describe the bug

Using the [Tailwind CC Extra](https://www.lazyvim.org/extras/lang/tailwind) is not generating any cmp completions when editing HTML. I get text and snippet suggestions, but no Tailwind classes. 

Example:
![image](https://github.com/LazyVim/LazyVim/assets/39483124/b1803f87-86a0-4c78-b81e-db03adc4acbf)

(Ghost text is copilot, not the LSP)

LSPInfo:
![image](https://github.com/LazyVim/LazyVim/assets/39483124/d6a14d2d-29d3-4b1d-8e21-299d6c749afb)
suggestions

### Steps To Reproduce

1. Add the extra to lazy.lua as per docs
2. Open HTML file
3. Add a class attribute to an element and start typing a TCCS class

### Expected Behavior

TCSS class names should appear in cmp

### Repro

```Lua
-- lazy.lua
require("lazy").setup({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    { import = "lazyvim.plugins.extras.lang.tailwind" },
    { import = "plugins" },
  },
})
```

**Comment by dpetka2001** [comment]
I tried with a fresh new Lazyvim starter template, enabled only the tailwind extra and cannot reproduce the issue. I think the issue lies with incorrect tailwind configuration. Steps I did to get it working with Lazyvim starter template:
```shell
1. mkdir ~/.config/lazytest
2. git clone https://github.com/LazyVim/starter ~/.config/lazytest
3. NVIM_APPNAME=lazytest nvim
4. Edit ~/.config/lazytest/lua/config/lazy.lua and import the extra with `{ import = "lazyvim.plugins.extras.lang.tailwind" },`
5. Close Neovim and start it again with the command provided in step 3 and wait for the extra to install. Open again `lazy.lua`, so that tailwind LSP server gets installed by mason. Close Neovim.
6. `touch tailwind.config.js` 
7. NVIM_APPNAME=lazytest nvim test.html and see that tailwind offers autocompletion for tailwind classes. 
```
I believe that tailwind LSP server, even though you're providing the cdn inside the script, somehow is not able to provide completions. If you create the `tailwind.config.js` it works as expected. I don't know the reason why, but this doesn't seem to be a Lazyvim issue. You should make an issue at Tailwind LSP repo, if you need further explanation as to why this is happening, because my knowledge comes only this far and I cannot provide you with further information.

**Comment by scottmckendry** [comment]
Thanks, I've added an empty `tailwind.config.js` file and cmp is displaying completions for Tailwind now. Bit annoying that it can't run without it. Appreciate your help :)
