### ISSUE TITLE
bug: Disabling flash doesn't work

### ISSUE THREAD

**Issue by jsatk** [LazyVim/LazyVim#1377]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.1

### Operating system/version

MacOS 13.5.1

### Describe the bug

Following the docs.

Creating a file in `lua/plugins/disabled.lua` and putting exactly this in there does not disable Flash. The entire reason I'm disabling it is because it overrides a default Vim key of `s`. It's still overriden/shadowed after adding this and when I open Lazy I see Flash is still loaded.
```lua
-- lua/plugins/disabled.lua
return {
  { "folke/flash.nvim", enabled = false }
}
```

### Steps To Reproduce

1. Create a file `lua/plugins/disabled.lua`.
2. Put the in there:
    ```lua
    return {
      { "folke/flash.nvim", enabled = false }
    }
    ```
3. Reload and notice Flash is still working.

### Expected Behavior

Flash stops working.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by abeldekat** [comment]
Hello @jsatk,

I started from scratch with LazyVim's [starter](https://github.com/LazyVim/starter) and added `disabled.lua` to the plugin's folder.

Result: Flash is disabled, as expected.

Perhaps, somewhere in the other modules in your plugins folder, flash is also configured **and** contains an explicit `enabled = true`, or `cond = true`.
You can also check your `lua/config/lazy.lua` for the presence of flash.

Best regards!

**Comment by dpetka2001** [comment]
Everything @abeldekat said. In your `~/.config/nvim` directory just do `rg 'flash'` and see the results for possible mentions of flash elsewhere. Also if the entire reason you're disabling it is because of `s` keybinding, then you might do the following
```lua
  {
    "folke/flash.nvim",
    keys = {
      { "s", mode = { "n", "x", "o" }, false },
	  {
        "<C-m>",
        mode = { "n", "x", "o" },
        function()
          require("flash").jump()
        end,
        desc = "Flash",
      },
    },
  },
```
to disable and change the keybinding to something else of your liking without uninstalling `flash` if you think that what it offers might be useful to your workflow.

**Comment by Silksofthesoul** [comment]
@jsatk 

Hi I had a problem with the search combinations for the `;` and `,` keys

I thought the reason was the `folke/flash.nvim` plugin.
But it turned out that the problem was in the `ggandor/flit.nvim` plugin

My file `lua/plugins/disabled.lua`:
```lua
return {
  -- disable trouble
  { "folke/flash.nvim", enabled = false, cond = false },
  { "ggandor/flit.nvim", enabled = false, cond = false },
}
```

Now the `;` and `,` keys work the way i'm used to
