### ISSUE TITLE
bug: Can't follow first step in neovim Lua guide with Lazyvim installed

### ISSUE THREAD

**Issue by elankath** [LazyVim/LazyVim#1478]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.2

### Operating system/version

MacOS 13.4

### Describe the bug

Just started following the Lua Concepts Guide at https://neovim.io/doc/user/lua.html#lua-concepts

With Lazyvim installed the very first step `:lua vim.print(package.loaded)` just hangs.

### Steps To Reproduce

1. Install lazyvim using getting started
2. Then execute `:lua vim.print(package.loaded)`
3. Your editor hangs. There is also an error saying "too many results"
4. This problem does not occur when Lazyvim isn't installed.

### Expected Behavior

The `package.loaded` table is displayed

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
It has something to do with `noice.nvim` and the way it displays the results. It must be setting some kind of limit in the results it can display because it shows them on floating windows (or maybe it's the floating windows limitation about how many lines they can display, I don't really know). If you disable `noice.nvim` you'll be able to do what you want. Maybe there's another way, but I fail to think of any. If you open an issue on the plugin's repo, maybe you'll have a better chance for a better and more complete answer.

**Comment by elankath** [comment]
ok will close this
