### ISSUE TITLE
feature: Easy way to keep LazyVim up to date

### ISSUE THREAD

**Issue by hiaw** [LazyVim/LazyVim#1563]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

I'm keen to try LazyVim but I don't see an easy way to keep LazyVim up to date. The installation process asks to clone the repo and then delete the `.git` folder. That means whatever updates LazyVim repo get, end user would have a hard time getting them. 

### Describe the solution you'd like

I like how NvChad have a command [NvChadUpdate](https://nvchad.com/docs/quickstart/install#update) that allows user to update without losing their customization. Their customization is put in a separate untracked folder.

### Describe alternatives you've considered

The alternative is to keep a git diff of whatever customization I've done and fix it everytime I pull from the LazyVim repo.

**Comment by hirotaka** [comment]
I'm not sure if my way is the right way. But I run the following command periodically to update it.

```
nvim --headless "+Lazy! update" +qa
```

**Comment by folke** [comment]
The installation instructions install `LazyVim/starter`.
That's just the bare minimal config for `lazy.nvim` that installs `LazyVim`.

`LazyVim` itself is the same as a regular plugin, so there is no need for a special update command. You update LAzyVim like you update any other plugin using `:Lazy`, the plugin mamager.

**Comment by andrearosasco** [comment]
After installing Lazy on another machine I've noticed I was missing out on some new features e.g. the dedicated command mode bar. When I tried to update the version on my machine through Lazy I still wasn't able to get the new features. What happened? Is an update feature actually required?

**Comment by dpetka2001** [comment]
What do you mean the dedicated command mode bar? An update feature is not required, because LazyVim gets updated through the Lazy UI, same as other plugins. I don't get what you're saying. I'm on latest LazyVim release by updating the plugin via Lazy UI and have all the features except those that are in HEAD and will be available on next stable release. Of course, you can also follow HEAD if you like so you immediate access to the merged commits without having to wait for the next release.

**Comment by AddictArts** [comment]
@folke and @dpetka2001 While the Lazy ui can update LazyVim, what about the dependencies? Will those be updated? for example snacks.nvim, Lazy will show it needs updates, so I individually update LazyVim plugin, does that update snacks as needed?

I suspect you suggest using "U" to update all plugins. However, that could update plugins you don't want updated. Now I have to track which are optional or my own and which are plugins LazyVim depends on. It would be much better to have an update that updates the main and dependencies. However, I may not be understanding what is meant above.

**Comment by dpetka2001** [comment]
LazyVim is just a plugin on its own. `snacks.nvim` is not a dependency of LazyVim. It will get updated on its own when there are updates. If you don't want to just `U` update all plugins, I suggest you lock specific plugins to certain versions/commit hashes, so that they don't get updated. If a plugin has an update and it's not locked, then `lazy.nvim` will update the plugin. Or go through the list of updates in `lazy.nvim` UI and just press `u` (lower case `U`) in the specific plugins that you want to update without touching the rest. 

I don't understand what you're trying to achieve though. I have everything up to date with no problems whatsoever. I don't know why you would want to not update a plugin, unless there's some kind of breaking change that is not fixed immediately. Even then you can just revert the plugin via `lazy.nvim` UI to a previous commit hash and lock the plugin to the last working commit hash until the breaking change gets fixed.

**Comment by AddictArts** [comment]
@dpetka2001 Yes LazyVim is a plugin on its own. However, when `Lazy` shows a bunch of plugin updates it can be confusing on which may go with or at the same version LazyVim is at.

For example: I see in `Lazy` a updated LazyVim, I just update it, just the LazyVim plugin. Is it the only one needing update? Probably not. How do I know which plugins and versions go along with any given version of LazyVim. Ideally, when updating LazyVIm you get the plugin versions that match its release.

**Comment by folke** [comment]
LazyVim does not pin versions of plugins.

**Comment by folke** [comment]
There are no plugin versions that LazyVim releases against.

If that's something you need, you should look into AstroNvim.

**Comment by AddictArts** [comment]
> There are no plugin versions that LazyVim releases against.

Poor choice of words on my part. There most certainly are versions / commit of distro included plugins as any feature or bug is completed and accepted into any given version of LazyVim. LazyVim does not track or manage those, it is just whatever is the latest main / HEAD / stable for each distro plugin right?
 
> If that's something you need, you should look into AstroNvim.

Thanks again, appreciate the suggestion and maybe I will, just took me time to get used to LazyVim and I appreciate it.

Nothing makes this opinion clear. As a distro it may It "has" many plugins; However, all should be updated and controlled individually as the user see's fit.

**Comment by dpetka2001** [comment]
`lazy.nvim` just tracks the latest HEAD of each plugin separately. `LazyVim` whenever the plugin has updates, `snacks.nvim` whenever the plugin has updates, `blink.cmp` whenever the plugin makes a new release, `fzf-lua` whenever the plugin has updates. It can't get simpler than that.

There are no distro plugins (except from specific cases in NvChad and I'm not sure that's the case any more because I don't follow what happens there). All plugins are created by users in the corresponding Github repo. If `lazy.nvim` is configured to install such a plugin, then it will automatically track its latest HEAD (unless you configure it otherwise, which is not suggested). 

> However, all should be updated and controlled individually as the user see's fit.

With regards to this I've already replied in my previous comment, quoting here
>  If you don't want to just update all plugins, I suggest you lock specific plugins to certain versions/commit hashes, so that they don't get updated. If a plugin has an update and it's not locked, then lazy.nvim will update the plugin. Or go through the list of updates in lazy.nvim UI and just press u (lower case U) in the specific plugins that you want to update without touching the rest.

You can press `u` (lowercase U) with your cursor on each plugin and only that plugin will get updated. Not the rest. You can choose what to update explicitly by doing so.
