### ISSUE TITLE
bug: Indenting issues 

### ISSUE THREAD

**Issue by tech0tron** [LazyVim/LazyVim#157]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

0.8.2

### Operating system/version

OpenSuSE Tumbleweed

### Describe the bug

I set shiftwidth and tabstop to 4 in my config file like so:

```lua
-- ~/.config/nvim/lua/config/options.lua
-- Options are automatically loaded before lazy.nvim startup
-- Default options that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/options.lua
-- Add any additional options here
local opt = vim.opt

opt.shiftwidth = 4
opt.tabstop = 4
```

When I indent a C file I'm writing using >> or gg=G it sets the indent correctly, but when I do :w it resets the indent back to 2 spaces.

### Steps To Reproduce

1. Set config file to what I have
2. Write a C file and indent to 4 spaces
3. Save and watch the indents go to 2 spaces

### Expected Behavior

When I save it should keep the indents at 4 spaces, or set any indents with 2 spaces to indents with 4 spaces.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")
-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
Works as expected for me. You must have an LSP or null-ls formatter active. You need to configure indent for those separately from Neovim.

**Comment by kogakure** [comment]
Maybe this is related. When using the LazyVim Starter, without any configuration, added plugins, or settings applied (here in a TSX file inside the component props), the cursor jumps not where one would expect it, but indents one level in. Might be from one of the included plugins.

<img width="441" alt="indent-bug" src="https://user-images.githubusercontent.com/5535/218092458-b8413933-74b1-42a0-85d7-5ec11ff5832d.png">

**Comment by folke** [comment]
Same answer. Might be the treesitter indent plugin. You may try disabling that.

```lua
  {
    "nvim-treesitter/nvim-treesitter",
   opts = {indent = {enable = false}},
}
```

**Comment by octaskin** [comment]
In case somebody ended up here but got disappointed...
You can override the defaults for null-ls (handles auto-formatting on save, thus responsible for formatting), which uses `clang_format` (probably)
```lua
return {
    "jose-elias-alvarez/null-ls.nvim",
    opts = function()
        local nls = require("null-ls")
        return {
            root_dir = require("null-ls.utils").root_pattern(".null-ls-root", ".neoconf.json", "Makefile", ".git"),
            sources = {
                -- Sets the desired indent width
                nls.builtins.formatting.clang_format.with({
                    extra_args = { "--style", "{IndentWidth: 4}" },
                }),
            },
        }
    end,
}
```
Noice! You just got the indent width to what it deserves to be instead of the despicable 2. 

_this might be already fixed as you read this dear future traveler..._

But now you get erronous warning messages 
```warning: multiple different client offset_encodings detected for buffer, this is not supported yet```
What the hell?! 
Maybe vscode.. Naah c'mon, we're too far deep. 

Oh here is a similar issue -> jose-elias-alvarez/null-ls.nvim#428, maybe they have a solution? Nope. 
Oh another, LunarVim/LunarVim#2597, maybe they will give us the solace we are seeking?? Sadly, not exactly. But some steps on the right direction.

Before we leave, let's take a moment to appreciate the patience and the kindness of @abzcoding, on that thread. I mean if you are reading this, omg my man :heart:. 

_The dev who responded to this issue can't imagine being half of that in his dreams._

Although getting a lesson on human values, we didn't get the _lazy_ solution we were hoping for, can't someone fix this for us? Who is going to really check what is written here and there, digest and apply the solution in context of this LazyVim thingy?

Don't worry fren, here you go
```lua
-- This overrides the default setting for clangd with offset encoding to utf-16
-- to prevent erronous warnings
return {
    "neovim/nvim-lspconfig",
    opts = {
        servers = {
            clangd = {
                capabilities = require("cmp_nvim_lsp").default_capabilities(),
                cmd = {
                    "clangd",
                    "--offset-encoding=utf-16",
                },
            }
        }
    }
}
```
End of the elephant in china-shop method that I applied to solve this issue.
By.

**Comment by sergiomb2** [comment]
> Same answer. Might be the treesitter indent plugin. You may try disabling that.
> 
>   {
>     "nvim-treesitter/nvim-treesitter",
>    opts = {indent = {enable = false}},
> }

so is a nvim-treesitter bug ,
