### ISSUE TITLE
I'm on vacation till April 28th 🏄‍♂️

### ISSUE THREAD

**Issue by folke** [LazyVim/LazyVim#1977]
I'm on vacation till April 14th.

I won't be checking GitHub and won't bring my laptop. See you all soon!

**Comment by grappas** [comment]
![obraz](https://media.tenor.com/iIs1G2PyzBcAAAAd/najman-marcin.gif)

**Comment by grappas** [comment]
https://media.tenor.com/iIs1G2PyzBcAAAAd/najman-marcin.gif

**Comment by appelgriebsch** [comment]
Hey @folke hope all is good? Do you need support reviewing all the different PRs that have been queued up here?

**Comment by folke** [comment]
All good, sorry for the delay on a lot of Neovim stuff!
I've been busy with traveling and lots training. When I'm not coding, I run ultra marathons :)

I just created a new release that includes two fixes for some things that were broken on nightly.
Busy day tomorrow and this weekend, but I'll have more time to get through the other things on Monday.

I'll keep this issue open till then.

**Comment by appelgriebsch** [comment]
@folke things I would like to see merged:

- https://github.com/LazyVim/LazyVim/pull/2213 (due to missing up-to-date java-test/java-debug packages in std mason)
- https://github.com/LazyVim/LazyVim/pull/2115 (project specific plugins - YAY)
- https://github.com/LazyVim/LazyVim/pull/2192
- https://github.com/LazyVim/LazyVim/pull/2178
- https://github.com/LazyVim/LazyVim/pull/2088
- https://github.com/LazyVim/LazyVim/pull/2071
- https://github.com/LazyVim/LazyVim/pull/2137
- https://github.com/LazyVim/LazyVim/pull/1980
- https://github.com/LazyVim/LazyVim/pull/1968

Cheers and have a great x-mas time :)

**Comment by leCoq42** [comment]
Is this project still alive?

**Comment by dpetka2001** [comment]
Well, there are still active contributors who try to help other people and also make PRs to improve the current state of LazyVim. Lazyvim is still operational as it is (with some minor exceptions to some specific lang extras that can be solved with local changes in your personal configuration if you incorporate some PRs yourself). Hopefully the maintainer will return soon.

**Comment by scarletquasar** [comment]
Are we in a moment where we just fork the project and keep the development in it instead of waiting for the guy?

**Comment by scarletquasar** [comment]
> @scarletquasar , it seems like there are [others](https://github.com/LazyVim/LazyVim/commits/main/) with the commit rights to this repository.

2 months ago :/

**Comment by trippel** [comment]
> Are we in a moment where we just fork the project and keep the development in it instead of waiting for the guy?

I honestly hope that @folke is alright and will show a sign of life anytime soon. LazyVim heavily relies on a bunch of his other great plugins and just forking it to incorporate the pile of PRs wouldn't address the whole set of problems.

**Comment by ckruse** [comment]
And also it would be a dick move to create a fork now. It's been just 2 months, LazyVim still works and we are not entitled to their time.

Just give them some slack.

**Comment by grappas** [comment]
Just wondering if any fellow contributor, close to @folke tried to contact him and just ask. I mean any other platform than github.

**Comment by surmish** [comment]
On his twitter, under likes, there are a couple of tweets that were 'liked' a few days ago. Hope he's okay.

**Comment by cerebrl** [comment]
My personal two cents (and I'm a complete nobody) is Folke has done more than enough to earn our trust. Even the design of LazyVim, `lazy.vim` and everything else he's built is in the spirit of flexibility and freedom to configure, extend, override to your heart's content. I'd recommend doing just that, rather than expecting updates to flow through the official pipeline.

I trust that Folke will officially make a statement if he feels he's no longer able to support this project. Or, he'll come back when he's ready and be his usual awesome self. Until then, I'm just going to apply updates and fixes locally, and hope that Folke is living his best life, whatever that may be.

❤️

**Comment by dpetka2001** [comment]
Hopefully [soon](https://twitter.com/Folke/status/1748243688650617104) :heart:

**Comment by ckruse** [comment]
@folke have fun :-)

**Comment by folke** [comment]
I'm off again till the end of the week
