### ISSUE TITLE
bug: can't go to the definition of function by gd

### ISSUE THREAD

**Issue by SheepyChan** [LazyVim/LazyVim#2003]
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.0-dev

### Operating system/version

Ubuntu 22.04.3 LTS in WSL1

### Describe the bug

I mainly develop by using C.
I installed the Lazyvim just after the Neovim following the installation guide.
When I open a `*.c` file in Lazyvim, the lua-language-server has been installed automatically, and I installed clangd in Mason manually.
and I had put the `compile_commands.json` in the root dir.
Then i restarted the Lazyvim, and open a `*.c` file, input   `gd`   , it goes to the declaration in `*.h` file.

This is my very first time using Lazyvim(even Neovim and vim), did I lose any configuration or something?
I'll appreciate that if u can help me for this issue.

### Steps To Reproduce

1. open a `*.c` file.
2. input `gd` for going to the definition of the function.
3. just go to the declaration in `*.h` file.

### Expected Behavior

go to the definition of the function in *c file.

**Comment by dpetka2001** [comment]
I tried with a simple `.c` and `.h` files generated from Chatgpt, because I'm not familiar with C, and definition went correctly to the definition in `main.c`. Then I pressed `gd` again while on definition and only then it took me to the declaration of the function in the header file. Bare in mind I didn't have any `compile_commands.json` existing. Just the the `.c` and `.h` files in the same directory. Maybe you have something different with your file structure? My guess would be it has something to do with your `compile_commands.json` file? Can you temporarily remove it and observe behavior?

**Comment by SheepyChan** [comment]
> I tried with a simple `.c` and `.h` files generated from Chatgpt, because I'm not familiar with C, and definition went correctly to the definition in `main.c`. Then I pressed `gd` again while on definition and only then it took me to the declaration of the function in the header file. Bare in mind I didn't have any `compile_commands.json` existing. Just the the `.c` and `.h` files in the same directory. Maybe you have something different with your file structure? My guess would be it has something to do with your `compile_commands.json` file? Can you temporarily remove it and observe behavior?
> 
> Edit: forgot to mention I just enabled the `lang.clangd` from `LazyExtras` and restarted Neovim for the installation to complete.

thx for ur reply.
I checked my `compile_commands.json`, it's really because I wrote a wrong root dir in it.
sorry for that, my bad.
