### ISSUE TITLE
bug: Neovim crashes at random

### ISSUE THREAD

**Issue by leaf541** [LazyVim/LazyVim#2050]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.4

### Operating system/version

MacOS 14.0

### Describe the bug

At some point neovim just crashes when I installed it with LazyVim, I've checked to log file and this is the only thing inside it:
`ERR 2023-11-22T17:30:10.253 ?.87054    chan_close_with_error:653: RPC: (null)`

### Steps To Reproduce

I don't know how to reproduce it.

### Expected Behavior

I don't know much about neovim but error code should be more concise.

**Comment by leaf541** [comment]
Hi @abeldekat, 
`: checkhealth` has no issues. I was checking how configs work and trying to implement telescope-file-browser. So I think that it was LUA lsp.

**Comment by dpetka2001** [comment]
Do you experience any crashes with default LazyVim configuration? If not, I'd suggest using `LazyExtras` to enable the extras you want, as when using `lazy.lua` to `import` them can cause potential issues if not importing them in the correct order (`LazyExtras` takes care of correct order according to Folke), although you should get an error message about one extra having to be loaded before another one if there were any conflicts (but there could be some edge cases that maybe this error message won't pop up, I'm just guessing). Your best chance to bisect this, would be to start with a fresh LazyVim starter template and take things slowly by enabling Extras and custom configuration one step at a time until you find the culprit that causes your Neovim to crash, although from past Folke's comments, a Neovim crash should almost never be caused by plugins and most frequent than not it's some problem with Neovim itself. Do you experience any crashes if you just install Neovim without LazyVim?

**Comment by amaanq** [comment]
If the crash is not hard to reproduce and happens often enough a gdb backtrace would be helpful (remember to compile neovim with debug syms!)

**Comment by averche** [comment]
I had a similar issue with random crashes while editing code a couple of weeks ago. I believe the issue was caused by one of the plugins updated in this https://github.com/averche/dotfiles/commit/7290b4d54f005f5fe34907b5db9fbf23fd925140 commit. After reverting the changes and then updating the plugins again recently (`nvim` => `l` => `<shift-U>`), the crashes seemed to have stopped. Hope this helps.

**Comment by leaf541** [comment]
Thnx everyone, I don't know exactly what caused  the issue but I removed extras from config and added them with `:LazyExtras`. Now everything works as intended.
