### ISSUE TITLE
feature: replace neo-tree's dangerous rm with trash command as default

### ISSUE THREAD

**Issue by amitlevy21** [LazyVim/LazyVim#2062]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

Hi,
I have just deleted 18 hours of work by accidentally deleting a folder with `neo-tree`.

`neo-tree` uses `rm` command to delete files and folders, which means its not trivial or easy to restore them after deletion.

I found this issue on `neo-tree`, unfortunately, its not the default, but we could include the configuration on lazyvim, to make it use trash command instead.
https://github.com/nvim-neo-tree/neo-tree.nvim/issues/202

### Describe the solution you'd like

For the sake of saving others people work, PLEASE, make neo-tree use `trash` command by default instead of the famous dangerous `rm` command.

### Describe alternatives you've considered

After my accident, I can of course add into my own config the feature of making `trash` default. But this would not save others who are not aware of the issue.

**Comment by dpetka2001** [comment]
I believe this should be made into an issue in the `neo-tree` repo to have such a default. What if something changes in the API it uses and the recipe is not applicable any more? In my opinion LazyVim should not implement such a thing, since I don't think it's the appropriate medium to implement this.

**Comment by amitlevy21** [comment]
Generally, I agree with your approach. I think this is an exception to the rule.
Such dangerous behavior on `neo-tree`  deletion functionality should be mitigated and controlled. If Lazy would use a different file manager plugin, why Lazy should allow such dangerous activity?

I have asked in `neo-tree` repo to address the issue in the link above. However, as an IDE, Lazy should prevent its core builtin plugins from doing such wrong. Or at least provide a mechanism to restore those files like VSCode and Pycharm for example have to restore file regardless of their status in version control

**Comment by dpetka2001** [comment]
LazyVim is not an IDE. It's just a plugin like all other plugins, that provides an IDE-like experience. Again, if something changes in the `neo-tree` API and that recipe no longer works any more, what is to become of this behavior? It would be safer for everyone for that behavior to be adopted by the plugin itself and LazyVim use the feature as provided. You can even just change the file manager with something of your own choosing in your own configuration. Users should change their configs according to their needs beyond what is provided by the defaults. In Neovim ecosystem, user is responsible for his own configuration and tries to prevent such pitfalls to his own workflow by changing whatever annoys him. In my personal opinion, I prefer this behavior and if something were to change I would prefer for `neo-tree` to expose both `delete` as it is and `delete_to_trash` as commands that the user would be able to choose from. Let the default behavior be `delete_to_trash`, but give the user the capability to use `delete` as it is now as well. That's just my personal opinion (as I've become used to this kind of behavior and am more careful to how I deal with my files).

**Comment by amitlevy21** [comment]
Understood. Thanks for addressing the issue.

**Comment by dpetka2001** [comment]
@amitlevy21 I'm just a user like yourself and just expressed my opinion. I'm not under any circumstances making any decisions for LazyVim. I hope you didn't feel pressed to close this issue because of the opinion I expressed. Please feel free to re-open the issue until the maintainer comes back and addresses your concerns. He might have an entirely different opinion than me. The point you want addressed is perfectly valid in my opinion and I hope you get it resolved one way or another.

**Comment by amitlevy21** [comment]
@dpetka2001 no problem :) thanks for clarifying that!

**Comment by dpetka2001** [comment]
@amitlevy21 I saw in the `neo-tree` issue that you linked, that they're not eager to accommodate this feature. So, the best option for you would be to implement it in your own user configuration, since I doubt LazyVim would implement something that's not officially supported by a plugin. It could may be an option to add something like a recipe in the LazyVim website, so that users know how to do that if they want to, but I doubt it will become default behavior in LazyVim. Again, I would like to **_emphasize_** that this is just my personal opinion.

**Comment by amitlevy21** [comment]
I ended up using https://github.com/bit-team/backintime#installation and https://wiki.gnome.org/Apps/DejaDup to backup the important code folders to other local destinations and to the cloud.

As this solves it for me, other people are going to have bad time if this is the way they need to learn about this behavior

**Comment by Parables** [comment]
VS Code has some extension called LocalHistory, that stores a snapshot of your files that have been modified anytime you save a file. If we could have something like that, I guess it would address such problems. It could be configured to save the snapshot to a different directory like your Home folder. 

An extra feature that can be added is to auto commit and push the snapshot folder anytime a new file is saved or at regular intervals.

**Comment by meicale** [comment]
oil.nvim is a good plugin.
