### ISSUE TITLE
feature: rust-tools.nvim is no longer maintained. Should be switched to Rustacean.nvim

### ISSUE THREAD

**Issue by RougeEtoile** [LazyVim/LazyVim#2113]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

rust-tools.nvim is no longer maintained, you can see that discussion [here](https://github.com/simrat39/rust-tools.nvim/issues/422). There is a new maintained fork called Rustacean [here](https://github.com/mrcjkb/rustaceanvim/tree/master).

### Describe the solution you'd like

Remove rust-tools from LazyVim and replace with rustacean.

### Describe alternatives you've considered

Do nothing.

**Comment by mati865** [comment]
Might be good to wait for https://github.com/mrcjkb/rustaceanvim/issues/53

**Comment by mrcjkb** [comment]
> Might be good to wait for [mrcjkb/rustaceanvim#53](https://github.com/mrcjkb/rustaceanvim/issues/53)

I probably won't get around to implementing that anytime soon, as its use case can be met with [`exrc`](https://neovim.io/doc/user/starting.html#exrc) or the ability to [load settings from a JSON file](https://github.com/mrcjkb/rustaceanvim#how-to-dynamically-load-different-rust-analyzer-settings-per-project).

**Comment by liamwh** [comment]
Added a comment on the PR's commit after trying it for a bit: https://github.com/appelgriebsch/LazyVim/commit/0333a7e335095f669abf0dad90d50014782c732b#commitcomment-137485810

**Comment by AThilenius** [comment]
Please forgive a somewhat ignorant nvim question, but what is the recommended way to get inlay hints back? After much head-smashing I finally got nvim 0.10 installed on my Nix system, but I can't get anything but the most basic of type hints to show up. It only shows hints for declared `let foo = something()` style statements, no hints for example are shown on call chains. I know `rust-tools` is deprecated, but it was still functional and nvim 0.10 is nightly.

**Comment by mrcjkb** [comment]
> Please forgive a somewhat ignorant nvim question, but what is the recommended way to get inlay hints back? After much head-smashing I finally got nvim 0.10 installed on my Nix system, but I can't get anything but the most basic of type hints to show up. It only shows hints for declared `let foo = something()` style statements, no hints for example are shown on call chains. I know `rust-tools` is deprecated, but it was still functional and nvim 0.10 is nightly.

See this discussion :smile: 
https://github.com/mrcjkb/rustaceanvim/discussions/46

**Comment by AThilenius** [comment]
Appreciate the link, but I've already gone through that. I tried both mentioned plugins for 0.9 and couldn't figure out how to get them to work with `LazyVim`. I had one working in a custom nvim config (based on lsp-zero). Tried 0.10 with `LazyVim` and the Rust `LazyExtra` enabled but that leads me to the problem above. Almost certainly a skill issue, but I've unfortunately exhausted my patience with broken tooling the last month, so probably going back to my old nvim setup.

**Comment by mrcjkb** [comment]
:thinking: I don't use LazyVim, so I'm not sure what could be causing these issues for you.

They work fine for me (plain neovim-nightly, also installed with Nix)

![scrot](https://github.com/LazyVim/LazyVim/assets/12857160/f323cab3-81cf-4b71-868c-66e9e6f8cfa7)

The API in neovim-nightly did change: It used to be `vim.lsp.inlay_hint()`, now it's `vim.lsp.inlay_hint.enable(/* boolean */)`.

Looking at the LazyVim `lang.rust` package, it appears it uses mason.nvim to install rust-analyzer.
In my experience, this can be problematic, mostly because it means you have to build your project twice (once for rust-analyzer and once when building with cargo, likely with different toolchains).
It's a bit of a wild guess, but maybe the mason installation comes with inlay hints disabled by default?
You could try playing around with the [server configuration](https://rust-analyzer.github.io/manual.html#inlay-hints).
