### ISSUE TITLE
bug: rust not installed into treesitter when using rust extra

### ISSUE THREAD

**Issue by ianschmitz** [LazyVim/LazyVim#2152]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.4

### Operating system/version

macos 14.1

### Describe the bug

I've installed the rust and neotest extras in my lazyvim config. When trying to open neotest i see the following error:

![CleanShot 2023-12-07 at 12 09 21](https://github.com/LazyVim/LazyVim/assets/6355370/c4dc23cb-7dc5-49fe-9042-dfbe678d774c)

Checking TSInstallInfo shows:

![CleanShot 2023-12-07 at 12 10 31](https://github.com/LazyVim/LazyVim/assets/6355370/b6a9af0c-dbd7-4b49-9b42-ca4b71c5a1a5)

### Steps To Reproduce

Here's my enabled extras if that helps:

![CleanShot 2023-12-07 at 12 10 52](https://github.com/LazyVim/LazyVim/assets/6355370/c51bb01e-4ac0-4b92-91dc-839ed6ed16ab)

### Expected Behavior

Reading the rust extra source it seems like everything should work out of the box as far as treesitter and neotest is concerned.

**Comment by dpetka2001** [comment]
Do you have somewhere in your config something like 
```lua
{
"nvim-treesitter/nvim-treesitter",
opts = {
ensure_installed = {
...
}
}
}
```
?

**Comment by ianschmitz** [comment]
I do! Great thinking. This was what i had when trying to enable nix support:

```lua
return {
  {
    "nvim-treesitter/nvim-treesitter",
    opts = {
      ensure_installed = {
        "nix",
      },
    },
  },
  {
    "neovim/nvim-lspconfig",
    opts = {
      servers = {
        ["nil_ls"] = {
          settings = {
            formatting = {
              command = { "nixpkgs-fmt" },
            },
          },
        },
      },
    },
  },
}
```

What would have been the appropriate way to add a plugin like i attempted above?

**Comment by dpetka2001** [comment]
See this [comment](https://github.com/LazyVim/LazyVim/discussions/2078#discussioncomment-7703428). If you use `vim.list_extend` then you won't have such problems in the future, since the final treesitter spec will merge your configuration with the LazyVim one (which also includes the treesitter fragments of spec throughout the extras).

**Comment by dpetka2001** [comment]
I don't think so, since both examples are needed to explain what is happening in each situation. One would overwrite the default configuration and the other would just extend it. It's up to the needs of the user which one he wants to use. Some users prefer overwriting the default and creating their own file hierarchy structure where they define things according to exactly what they want. Some of LazyVim's defaults might not be wanted. So, you just end up overwriting things according to your needs.
