### ISSUE TITLE
how to change cursor shape on nvim with lua language ?

### ISSUE THREAD

**Issue by iafshinafshin** [LazyVim/LazyVim#2261]
how to change cursor shape on neovim with lua language ?

look like this :
![Screenshot from 2023-12-27 20-16-40](https://github.com/LazyVim/LazyVim/assets/138600371/9fe04493-6af6-4051-b8ab-88ded5cd0a1d)

**how to use underline for cursor for insert mode and visual mode on lua language ?**

**Comment by dpetka2001** [comment]
> Before reporting an issue, make sure to read the [documentation](https://github.com/folke/LazyVim) and search [existing issues](https://github.com/folke/LazyVim/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc). Usage questions such as "How do I...?" belong in [Discussions](https://github.com/folke/LazyVim/discussions) and will be closed.

Usage questions belong in the Discussions. Kindly close this issue since it's not a LazyVim issue. 

Also for what you want to achieve, you should read `:h 'guicursor'` for more info. For example for insert mode, 
you could do something like `vim.opt.guicursor = { i:hor1 }`. Look at the help file what other options and values 
are available.

**Comment by iafshinafshin** [comment]
i used that 
thank you 
your code an was problem i used this code and bit change the your code :  **`vim.opt.guicursor = { "i:hor1" }`**

**Comment by dpetka2001** [comment]
Please close the issue if it is resolved and next time you should use the Discussions for such questions.
