### ISSUE TITLE
bug: colorscheme with preview execution error

### ISSUE THREAD

**Issue by loclink** [LazyVim/LazyVim#2265]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.4

### Operating system/version

macos 14

### Describe the bug

When I press `<leader>uC`, I cannot preview the color scheme in the list, press Enter to confirm the selection and an error is reported. I have not configured the telescope in any way

<img width="1258" alt="image" src="https://github.com/LazyVim/LazyVim/assets/106688231/81cbdde3-515b-4628-ad47-72828d3770b0">

### Steps To Reproduce

1. `<leader>uC`
2. select colorscheme
3. Enter 

### Expected Behavior

Previews and switches work fine

**Comment by dpetka2001** [comment]
This seems to have something to do with Telescope after latest update. [This](https://github.com/nvim-telescope/telescope.nvim/commit/aacaa9cd031da83ce08d8fa5f19083d731f7f62c) seems to be the root of cause. Best to open an issue at Telescope repo and close this, since it has nothing to do with LazyVim.
