### ISSUE TITLE
bug: Colorscheme preview

### ISSUE THREAD

**Issue by rubiin** [LazyVim/LazyVim#2405]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5

### Operating system/version

linux

### Describe the bug

I have the following colorschemes installed
https://github.com/rubiin/init.lua/blob/master/lua/plugins/ui/colorscheme.lua

But the the colorscheme preview  doesnt seem to show them
![image](https://github.com/LazyVim/LazyVim/assets/8222059/76fc595d-7726-439c-b22d-520bdd4fbe49)

### Steps To Reproduce

install any colorscheme and try to see if it gets listed on colorscheme toggle preview

### Expected Behavior

Should list the colorscheme

**Comment by folke** [comment]
That's expected behavior.

`:Telescope colorscheme` can only show loaded colorschemes.

You could do `:Lazy load all` to load all plugins and then list the colorschemes to show them all.

**Comment by dpetka2001** [comment]
@rubiin You could also use the `keys` section of lazy.nvim for lazy-loading and define the same key for all colorschemes, so that they are available when you want. 
```lua
keys = {
      { "<leader>uC", Util.telescope("colorscheme", { enable_preview = true }), desc = "Colorscheme with preview" },
    },
```
Something like this in all your installed colorschemes using the same key and they will be lazy-loaded when you open the Telescope colorscheme picker.
