### ISSUE TITLE
bug:  Tab completion not working

### ISSUE THREAD

**Issue by Albert24GG** [LazyVim/LazyVim#244]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

0-.8.3

### Operating system/version

Linux 6.1.11

### Describe the bug

When trying to use autocompletion, pressing tab just inserts a space, and thus I have to use the arrows and enter to have access to those completions. I tested this, and with other configs and this feature works just fine.

### Steps To Reproduce

1. Open neovim.
2. Write something and try to use tab completion.

### Expected Behavior

Autocomplete code.

**Comment by dpetka2001** [comment]
The `Tab` completion is not default behavior in Neovim and `nvim-cmp`. There is an example in the [`docs site`](https://www.lazyvim.org/configuration/examples) right in the bottom that you can use to configure `Tab` to use it in autocompletion.

**Comment by Albert24GG** [comment]
I am already using the `example.lua` plugins config you linked and the tab completion is not working.

**Comment by pprotas** [comment]
In LazyVim you can use `Ctrl-f` and `Ctrl-n` to choose the completion and press `<CR>` (enter) to select

**Comment by folke** [comment]
Are you sure you added the code exactly as specified in https://www.lazyvim.org/configuration/recipes#supertab ?

You also need the LuaSnip part,  as specified in the docs, otherwise it won't work.

With those two snippets, it works as expected.

Also, next time, please post these types of user questions to the github discussions. This is not a bug.

**Comment by eTzmNcbkrng** [comment]
For anyone coming to this in the future, the example config that is mentioned as being on the docs site has been removed over a series of commits. Here is a link to what this example looked like at the time the comment was made:
https://github.com/LazyVim/lazyvim.github.io/blob/08d5ebc7dbf422bce1716e9dc29603e373e637c4/docs/configuration/examples.md

I *think* it was removed because lazyvim, changed the default from nvim-cmp to blink.cmp

As a new user, I find this behaviour infuriating, I type a line of code then press enter to start a new line and it replaces what I typed with whatever was in the autocomplete box, I have to undo the change, exit insert mode, go down a line and go back into insert mode.

I think I've got this working the way I want by creating this ~/.config/nvim/lua/plugins/blink.lua:
```lua
return {
  "saghen/blink.cmp",
  optional = true,
  opts = {
    keymap = {
      preset = "super-tab", -- "default", "super-tab", or "enter" if you prefer
      ["<CR>"] = {}, -- unmap Enter (so it just inserts a newline)
      -- Optional: keep <C-CR> for accepting if you want
      ["<C-CR>"] = { "accept", "fallback" },
    },
    -- Optional: don't auto-select the first item
    completion = {
      list = {
        selection = { preselect = false },
      },
    },
  },
}
```
