### ISSUE TITLE
bug: VimEnter autocmd not running

### ISSUE THREAD

**Issue by RunnersNum40** [LazyVim/LazyVim#2592]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.4

### Operating system/version

Ubuntu

### Describe the bug

I have been trying to configure some `VimEnter` auto commands and nothing seems to be triggering. I've created a minimal version of this issue. The auto command in this snippet never appears to run. Curiously it works with `:doautocmd VimEnter`.

```lua
vim.api.nvim_create_autocmd("VimEnter", {
  callback = function()
    print("VimEnter autocmd")
  end,
})
```

### Steps To Reproduce

1. Add code snippet to `lua/config/autocmds.lua`
```lua
vim.api.nvim_create_autocmd("VimEnter", {
  callback = function()
    print("VimEnter autocmd")
  end,
})
```
2. Restart nvim session

### Expected Behavior

The message "VimEnter autocmd" should be sent.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
vim.api.nvim_create_autocmd("VimEnter", {
  callback = function()
    print("VimEnter autocmd")
  end,
})
```

**Comment by dpetka2001** [comment]
This is because the `autocmds` in LazyVim depend when they execute on if you invoke Neovim with a file argument or not. If you specify a file argument then the `autocmds` will execute immediately. If you don't specify a file argument, then they will be executed on `VeryLazy` event and that's what you're observing. So, if you do `nvim init.lua` for example and then do `:messages` you will see the message from the autocmd.

**Comment by RunnersNum40** [comment]
Is there a way of running something upon open regardless of the type of invocation? 

To clarify, is `VimEnter` not being triggered in this case or are the LazyVim user configured auto commands not being loaded until after the `VimEnter` event? If it's the former what's the benefit of this behaviour because it's quite confusing. If it's the latter should I just move my auto command to `init.lua`?

**Comment by RunnersNum40** [comment]
I tried placing the auto command in my `init.lua` underneath `require("config.lazy")`. This fixed the issue. I assume that it's the former of the cases I commented above ("LazyVim user configured auto commands not being loaded until after the `VimEnter` event").

While this does solve the problem is there a cleaner way to do it? It seems messy to have to put a specific type of auto command in a separate document. My auto commands are not that extensive. Could I just load my `lua/config/autocmds.lua` file from `init.lua` or should I avoid this to prevent loading things twice?

**Comment by dpetka2001** [comment]
The LazyVim autocmds are being triggered on VeryLazy event when opening Neovim without file arguments, so the `VimEnter` autocmds are moot at this point since it's already passed. This behavior was chosen by the maintainer for performance reasons when opening Neovim, so that the UI doesn't get blocked. I don't have much knowledge about this myself to be honest. But moving your autocmd to `init.lua` could work or choosing a different event to load what you want (ie `BufReadPre`, `BufReadPost`, `BufNewFile` etc). Don't require `lua/config/autocmds.lua` from your `init.lua`. Just put only your specific autocmd if that's definitely what you want.

**Comment by dpetka2001** [comment]
Why do you load your autocmds on `VimEnter` instead of some other event? The only time I've seen `VimEnter` event being used is for dashboards for example. Everything else gets loaded either on `VeryLazy` or some other event that happens after `UIEnter`.

**Comment by RunnersNum40** [comment]
The main thing I am trying to setup is automatically loading the directory session with `require("persistence").load()`. Is there and event that runs once, automatically, and right after `VeryLazy`?

This is the auto command I was struggling with.

```lua
-- restore the session for the current directory
vim.api.nvim_create_autocmd("VeryLazy", {
  group = vim.api.nvim_create_augroup("persistence", { clear = true }),
  callback = function()
    require("persistence").load()
  end,
  nested = true,
})
```

**Comment by GitMurf** [comment]
I am curious to know this as well. I just want an autocmd to be able to run before having to "do anything" like load a buffer / file, run a command etc. I have the default lazyvim dashboard shown at startup. Essentially I just want to have an autocmd trigger when my dashboard is loaded (or shortly thereafter) so that it triggers before I take any action in nvim. @RunnersNum40 does this sound similar to what you are wanting too? what events can we add an autocmd to that trigger after neovim is loaded but before I take any action?

**Comment by dpetka2001** [comment]
@RunnersNum40 

You could take advantage of the dashboard being loaded on `VimEnter` and do something like following
```lua
return {
  {
    "nvimdev/dashboard-nvim",
    opts = function()
      if vim.fn.argc(-1) == 0 then
        vim.defer_fn(function()
          require("persistence").load()
        end, 100)
      end
    end,
  },
}
```
The `vim.defer_fn` is needed to defer the loading of the session just enough, so that `nvim-lspconfig` gets loaded and the LSP server can attach to the buffer. Otherwise, the first buffer will not have an LSP server attached to it, because `VimEnter` happens before `LazyFile`, which is where `nvim-lspconfig` is loaded.

**Comment by GitMurf** [comment]
@RunnersNum40 I think I figured out a solution for running things on startup. Looks like the `LazyVimKeymaps` custom event is triggered essentially right after the autocmds are loaded on startup.

```lua
vim.api.nvim_create_autocmd("User", {
  pattern = "LazyVimKeymaps",
  callback = function()
    -- using vim.schedule to run this after lazyvim loads
    -- it essentially waits for the next "event loop"
    vim.schedule(function()
      -- do some stuff after lazyvim loads
      vim.notify("LazyVimKeymaps autocmd pattern triggered")
    end)
  end,
})
```

**Comment by dpetka2001** [comment]
@GitMurf 

Nice find. Thanks for sharing. I would still suggest to guard the requiring of `persistence` only when there are no file arguments, otherwise the session will be loaded even if you want to open Neovim with a specific file argument, which is counter-intuitive in my opinion. But the OP can do as he pleases.

**Comment by jaredmcateer** [comment]
I have a similar issue where I want [venv-selector](https://github.com/linux-cultist/venv-selector.nvim#-automate) to automatically look for a pyproject.toml and select a python virtual environment when I load vim. I don't know if there is a better way than @GitMurf suggested for what I want to achieve but listening for `LazyVimAutocmds` does the trick for me.

This line in the init.lua creates events `LazyVimAutocmds`, `LazyVimOptions`, and `LazyVimKeymaps`.  If you want to hook into something more closely related to what you're doing.

https://github.com/LazyVim/LazyVim/blob/91126b9896bebcea9a21bce43be4e613e7607164/lua/lazyvim/config/init.lua#L246

**Comment by GitMurf** [comment]
@jaredmcateer nice find! This is great. So if I am understanding this correctly, by using LazyAutoCmd we are basically saying "as soon as you create the autocmd and load it, please run it for me"?

**Comment by RunnersNum40** [comment]
Good to know about the `LazyVimKeymaps` event. My solution before that suggestion was just to create a new file in the `config` dir meant only for auto commands and load it after lazy in from `init.lua`.

While `LazyVimKeymaps` work in this case IMO it's a little messy since that's not really the event that we're meaning to use. How would I go about suggesting a new event such as `LazyEnter` that's triggered after `VeryLazy`?

**Comment by RunnersNum40** [comment]
> @GitMurf
> 
> Nice find. Thanks for sharing. I would still suggest to guard the requiring of `persistence` only when there are no file arguments, otherwise the session will be loaded even if you want to open Neovim with a specific file argument, which is counter-intuitive in my opinion. But the OP can do as he pleases.

Good suggestion. I also ended up adding a guard to avoid this behavior in the home directory since I'll usually enter nvim from there for one-off text writing uses.

**Comment by GitMurf** [comment]
> ...How would I go about suggesting a new event such as `LazyEnter` that's triggered after `VeryLazy`?

I have no idea! I figure the conversation here is probably a good first step and then maybe open a new gh issue as a feature request? 🤷🏻‍♂️

And btw I agree with you completely that a "VeryLazyExit" or "PostVeryLazy" event is exactly what I am actually after :)

**Comment by dpetka2001** [comment]
@GitMurf 
> This is great. So if I am understanding this correctly, by using LazyVimAutocmds we are basically saying "as soon as you create the autocmd and load it, please run it for me"?

According to my understanding that's not what's happening. The `LazyVimAutocmds` get executed inside the `load` function, which is responsible for loading the `autocmds` either immediately (when invoked with a file argument) or lazily (when invoked without a file argument). The difference is that it's a `User` event that will load the `LazyVimAutocmds` pattern (which you define in your own `User` autocmd). It will still get executed, since it's explicitly called within the `load` function. 

The problem with `VimEnter` is that when the autocmds are loaded lazily (when invoked without a file argument), they are set to execute on `VeryLazy` and at that point `VimEnter` has already passed by, thus making the autocmd moot at that point in time.

**Comment by folke** [comment]
`autocmds.lua` are typically loaded after `VimEnter`.
Just use `VeryLazy` instead.

**Comment by GitMurf** [comment]
> `autocmds.lua` are typically loaded after `VimEnter`.
> 
> Just use `VeryLazy` instead.

@folke thank you for the response but the problem is we need something that can guarantee all the plugins / verylazy stuff is loaded. If I use VeryLazy you have no clue the order it goes in and no clue if the stuff you need loaded first is complete before your autocmd runs. Does that make sense? Basically we would want a "PostVeryLazy" so that you can guarantee it triggers after all plugins / verylazy stuff if finished.

**Comment by dpetka2001** [comment]
@GitMurf Can't you just use a `User` autocmd on `VeryLazy` and in the callback use `vim.schedule`? I believe this would make it so, that your autocmd is the last one executed.

**Comment by GitMurf** [comment]
> @GitMurf Can't you just use a `User` autocmd on `VeryLazy` and in the callback use `vim.schedule`? I believe this would make it so, that your autocmd is the last one executed. Like you did in the example you also provided in one of your previous posts.

Maybe, but it seems fragile and I assume some of VeryLazy is probably doing its own vim.schedule as part of the lazy loading process? Also plugins themselves may be using vim.schedule during loading. Assumptions but I don't know for sure.

**Comment by folke** [comment]
`VeryLazy` already runs after `VimEnter`.

What's the actual problem you're trying to solve here?

If you just want the autocmd to run on `VimEnter`, then just add it to your `options.lua`. 

That will execute before `VimEnter`.
