### ISSUE TITLE
bug: Installing does nothing and opens default nvim

### ISSUE THREAD

**Issue by DanielHammerin** [LazyVim/LazyVim#2816]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5

### Operating system/version

Windows 10 22H2

### Describe the bug

Following the install instructions by cloning the starter, removing the `.git` and then running `nvim` command in windows `terminal` results in default nvim opening.
![image](https://github.com/LazyVim/LazyVim/assets/11715800/8742b7c8-7d8f-4b6c-b1c9-9194c7c2e923)

### Steps To Reproduce

1. Follow the install instructions
2. run the command `nvim`
3. default nvim config (no config) opens and nothing more.

### Expected Behavior

I expect lazyvim to initialize and install the required packages and dependencies.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

### EDIT:
I had set `$XDG_CONFIG_HOME` environment variable to a custom location. Removing this fixes the problem.
But shouldn't we be able to do this if we want to install one or more configs?
Sorry if this is a nooby question. I'm not very familiar with nvim config setup on WIndows. I primarily use linux where this is super easy, but i'd like to be able to use nvim/lazyvim on my windows machine as well.

**Comment by dpetka2001** [comment]
This is not a problem with LazyVim, rather with Neovim itself. 

Neovim expects the $XDG directories to be in standard locations based on the OS it's installed. See `:h xdg`. I don't know about Windows (don't use them), but on Linux you don't change your $XDG_CONFIG_HOME directory to install multiple configs. You simple install the distro you want in a directory in $XDG_CONFIG_HOME and then start Neovim with `NVIM_APPNAME=dir_name nvim`, so that it can create the corresponding `data`, `state` and `cache` directories without intervening with the default values.
