### ISSUE TITLE
bug: can't configure telescope extension project

### ISSUE THREAD

**Issue by alexander-born** [LazyVim/LazyVim#283]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

0.8.1

### Operating system/version

Ubuntu 20.04

### Describe the bug

I can't configure the telescope extension https://github.com/nvim-telescope/telescope-project.nvim

### Steps To Reproduce

1. create /lua/plugins/telescope.lua
```lua
return {
  {
    "nvim-telescope/telescope.nvim",
    dependencies = {
      { "nvim-lua/plenary.nvim", lazy = true },
      {
        "nvim-telescope/telescope-project.nvim",
        config = function()
          require("telescope").load_extension("project")
        end,
      },
    },
    opts = {
      extensions = {
        project = {
          base_dirs = { { path = "~", max_depth = 4 } },
        },
      },
    },
  },
}

```

### Expected Behavior

Telescope extension project is configured.

**Comment by alexander-born** [comment]
It works with this `repro.lua`

```lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")
-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
        vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
        vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
        "folke/tokyonight.nvim",
        "folke/LazyVim",
        {
                "nvim-telescope/telescope.nvim",
                dependencies = {
                        { "nvim-lua/plenary.nvim" },
                        {
                                "nvim-telescope/telescope-project.nvim",
                                config = function()
                                        require("telescope").load_extension("project")
                                end,
                        },
                },
                cmd = "Telescope",
                keys = { { "<leader>sa", false } },
                config = function()
                        local telescope = require("telescope")
                        telescope.setup({
                                extensions = {
                                        project = {
                                                base_dirs = { { path = "~", max_depth = 4 } },
                                        },
                                },
                        })
                        telescope.load_extension("project")
                end,
        },
}
require("lazy").setup(plugins, {
        root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by alexander-born** [comment]
Is it incorrect to load telescope extensions like I did before? I got this from the documentation here: https://www.lazyvim.org/configuration/recipes#add-telescope-fzf-native

**Comment by dpetka2001** [comment]
I have almost your configuration in the first post
```lua
  {
    "nvim-telescope/telescope.nvim",
    dependencies = {
      {
        "nvim-telescope/telescope-project.nvim",
        keys = {
          { "<C-p>", "<cmd>lua require'telescope'.extensions.project.project{}<cr>", desc = "Telescope Project" },
        },
        config = function()
          require("telescope").load_extension("project")
        end,
      },
    },
    opts = {
      extensions = {
        project = {
          base_dirs = {
            { path = "~/Desktop/Projects/", max_depth = 4 },
          },
        },
      },
    }
  }
```
and it works fine for me.

**Comment by alexander-born** [comment]
> and it works fine for me.

I tested your config just now and it does not work for me :(
`:Telescope project` works, but it does not list any projects.

**Comment by alexander-born** [comment]
I did yes.

**Comment by dpetka2001** [comment]
Did you just copy/paste my config? I changed the `path` variable to be where my projects are. Maybe you should set it to whatever you like?

**Comment by dpetka2001** [comment]
Delete `telescope-projects.txt` and `telescope-workspaces.txt` and then start Neovim. `telescope-workspaces.txt` also gets created from the `telescope-project` extension so maybe that interferes with something?

**Comment by alexander-born** [comment]
Thanks for you help :) But I did the following before testing your config changes.
```bash
rm -rf ~/.local/share/nvim ~/.local/state/nvim ~/.cache/nvim
```

**Comment by dpetka2001** [comment]
Doing so removes all the plugins from LazyVim as well. Did you run `Lazy` to install the necessary plugins again? If yes, then I don't know what else to tell you since the above config works just fine for me. Maybe you should go with the config that you posted before me, which seems to solve your problem.

**Comment by alexander-born** [comment]
Lazy automatically pulls the plugins. I will close as [this](https://github.com/LazyVim/LazyVim/issues/283#issuecomment-1433352997) solves my problem.

**Comment by folke** [comment]
Since **telescope-project** depends on an option set to telescope, it indeed has to be loaded **after** telescope. So your fix for that seems fine

**Comment by dpetka2001** [comment]
But if you set it as a dependency to telescope doesn't that mean that it's loaded after telescope. My config works just fine the LazyVim way without having to specify the `config` function with `requires`. Something else must be going on, but since he fixed it it's ok. Still the recipe for `fzf` in the docs can be applied in other telescope extensions as well. Also since the `config` function of the extension is `require("telescope).load_extensions("project")` doesn't that require for telescope to be loaded already? At least that's how I understand it but of course I may be wrong, so please feel free to correct me.

**Comment by folke** [comment]
@dpetka2001 but looking at your config, if the first thing you do is run `<c-p>`, so if you didn't do any other telescope commands, then tat would lead to the `projects` plugin being loaded, which means:

- it will internally `require("telescope")` 
- that will autoload the telescope plugin, and as such its config
- so by the time the projects `config` runs, the telescope one would already have been set up

If you'd instead do something like `Telescope`, then the following would happen:
- it will load telescope dependencies
- the dep is projects, so that will load
- projects will internally `require("telescope")`
- but since we are already loading `telescope`, it will bail out and just continue
- projects `config` will run
- telescope `config` will run

I hope this makes more sense :)
