### ISSUE TITLE
feature: Plz don`t disable lewis6991/gitsigns.nvim with mini_diff

### ISSUE THREAD

**Issue by WikiLiu** [LazyVim/LazyVim#2914]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

To be honest, both of two git plugins are very useful in respective areas of each one. Mini_diff can show diff information more clearly and needn`t open new window. But gitsigns has so much function such as git blame, stage buffer, etc.
I think the two git plugins can exit in the same time. And I known that can exactly reloading gitsigns.nvim in my personal config.

### Describe the solution you'd like

as on

### Describe alternatives you've considered

as on

**Comment by rubiin** [comment]
Git signs is enabled by default whereas minidiff, you have to enable via extras. So there  is nothing disabled by default

**Comment by dpetka2001** [comment]
@rubiin The `mini-diff` Extra does indeed disable `gitsigns` if the user enables the Extra. See [here](https://github.com/LazyVim/LazyVim/blob/97480dc5d2dbb717b45a351e0b04835f138a9094/lua/lazyvim/plugins/extras/editor/mini-diff.lua#L3-L6).

**Comment by WikiLiu** [comment]
@dpetka2001 Yeap, Is it necessary to banning gitsigns  for enabling mini-diff ? I mean if there is no conflict and increased Extra,  is it possible to enable both?

**Comment by rubiin** [comment]
I think if there is no conflicting keymap then enabling both should not be a problem

**Comment by dpetka2001** [comment]
@WikiLiu I'm just a regular user like you, not affiliated with this project. I don't make any decisions. You'll just have to wait for the maintainer's reply on this request of yours :smile: 

@rubiin There are conflicting keymaps, because both use `gh` namespace (`mini-diff` has its mappings internally even if they are not defined by LazyVim). So, I believe something would have to change even slightly. Maybe @WikiLiu could tell us about her experience of what happens when she presses `gh` with both of the plugins enabled. Which one takes precedence?

**Comment by WikiLiu** [comment]
@dpetka2001 @rubiin I test simply, no any error or remind thrown. And gh did work for stash/reset, but I don`t know which one effects it. Maybe test it by insert debug info or print to lua?

**Comment by dpetka2001** [comment]
@WikiLiu I was wrong. `mini-diff` uses directly `gh`, whereas `gitsigns` uses `<leader>gh`, so there should be no conflicts. Sorry about that.

**Comment by miladhatami1393** [comment]
Related

**Comment by folke** [comment]
Both gitsigns and mini.diff add signs to the buffer.
That's asking for issues.
If you don't want that then don't enable the `mini.diff` extra and just copy the spec to your own config.
