### ISSUE TITLE
bug: Editorconfig is ignored in Markdown files

### ISSUE THREAD

**Issue by awilkins** [LazyVim/LazyVim#3153]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

neovim-0.10.0~ubuntu1+git202401272103-2cd76a758-971e32c87

### Operating system/version

Ubuntu 20.04.3

### Describe the bug

Editorconfig settings are ignored in Markdown files. Using nightly vim and relying on the native Editorconfig support.

Settings for e.g. js files appear to work OK.

### Steps To Reproduce

1. Create an editorconfig
```editorconfig
root = true

# Unix-style newlines with a newline ending every file
[*]
end_of_line = lf
insert_final_newline = true
indent_style = space
indent_size = 2

[*.js]
indent_size = 3

[*.md]
indent_size = 4
trim_trailing_whitespace = false
```
2. vim -u /tmp/nothing test.md
3. Type `i<Tab>indented<Esc>wq<Enter>`
4. vim test.md
5. Type `o<Tab>Indented<Esc>wq<Enter>`

I tried doing this by passing ex commands - ie

```
vim -c 'let @a = "o<tab>indented^["' -c "norm @a" -c "wq" -u /tmp/nothing test.md
vim -c 'let @a = "o<tab>indented^["' -c "norm @a" -c "wq" test.md
```

... but the Ex commands end up running before enough of LazyVim has loaded and the indents are both OK.

### Expected Behavior

Expected file content

```
    indented
    indented
```

Actual file content

```
    indented
  indented
```

### Repro

```Lua
-- My Lua skillz are not this mad
```

**Comment by dpetka2001** [comment]
@folke 

This has something to do with function `lazy_file` maybe?? When I try the example the OP gave without file arguments, it works correctly. When I try it with file arguments, then it doesn't work correctly. 

Without file arguments I get 
```
set ts?   tabstop=4
	Last set from ~/.local/share/bob/nightly/nvim-linux64/share/nvim/runtime/lua/editorconfig.lua line 125
```
whereas with file arguments I get 
```
set ts?   tabstop=2
	Last set from ~/.local/share/bob/nightly/nvim-linux64/share/nvim/runtime/ftplugin.vim line 17
```
I tried to do in `lazy_file` function the same as with `filetypedetect`, because if you print out the `augroups` you can see that `editorconfig` is listed, like so 
```lua
      local groups = vim.tbl_filter(function(t)
        return not vim.tbl_contains({ t }, "filetypedetect") and not vim.tbl_contains({ t }, "editorconfig")
      end, augroups)
```
but it doesn't seem to work. The problem still remains and I get the values for `tabstop` with and without file arguments as what I stated earlier. The only way I could make it work was either by removing `BufReadPre` from `M.lazy_file_events` or by commenting out 
```lua
        if vim.bo[event.buf].filetype then
          Event.trigger({
            event = "FileType",
            buf = event.buf,
          })
        end
```
Really no idea why this happens with my limited knowledge. I thought by just excluding `editorconfig` from `skips` would make it work like with `filetypedetect`. 

I also temporarily commented out the `lazy_file` function from `util.plugin.setup` and although I did get errors for `LazyFile` (because the specs obviously couldn't find it), it did work also correctly.

Just wanted to share my findings, in the hope that maybe you find something useful of what I said and probably be able to come up with a proper solution about this.

**Comment by folke** [comment]
Probably has to do with Neovim's builtin ftplugin for markdown. tpope added quite a bit of opinionated settings in there.

I'll look into it.

I may just disable LazyFile, since that leads to quite a bit of issues...

**Comment by folke** [comment]
possibly related:

- https://github.com/neovim/neovim/pull/28736
- https://github.com/neovim/neovim/issues/28484

**Comment by dpetka2001** [comment]
Maybe we just shouldn't trigger the `FileType` event for Markdown specifically?

**Comment by dpetka2001** [comment]
@folke Some further information. After reading the links that you mentioned and then following another link in one of the issues I found this [comment](https://github.com/neovim/neovim/pull/27425#issuecomment-1937843490). 

Based on this I did
```lua
      if vim.api.nvim_buf_is_valid(event.buf) then
        if vim.bo[event.buf].filetype then
          Event.trigger({
            event = "FileType",
            buf = event.buf,
          })
        end
        Event.trigger({
          event = event.event,
          exclude = skips[event.event],
          data = event.data,
          buf = event.buf,
        })
      end
```
so that the `FileType` event happens first and then we trigger the other events (`BufReadPost`, `BufNewFile` etc) and it seems to be working correctly along with the change of excluding `editorconfig` from `skips` table. 

Would you like to take further look into this? Should I submit a PR based on these findings?

**Comment by folke** [comment]
Should be fixed now!
