### ISSUE TITLE
bug: key map "Visual Character Mode" ->  "Inside textobject" -> "(" problem in javascript file

### ISSUE THREAD

**Issue by ChrisChou-freeman** [LazyVim/LazyVim#3170]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.5

### Operating system/version

MacOS 14.4.1

### Describe the bug

```js
// javascript or typescript
app.on('before-quit', (event) => {
  appStateManage.isQuitingAction = true
})
```
use "Visual Character Mods" try to select first parentheses's inside text will jump to second one.

### Steps To Reproduce

in this javascript code example above,  press v in Normal mode when cursor hover on first parentheses, then press i and `(`

### Expected Behavior

can normally select first parentheses's inside text 

### Repro

```Lua
default config
```

**Comment by dpetka2001** [comment]
That functionality comes from [mini.ai](https://github.com/echasnovski/mini.ai). Create an issue at the plugin's repo, as this can't be fixed here. And I also don't know if this is something inherent with Lua patterns, but I'm sure the plugin's maintainer will give a more appropriate answer.

**Comment by ChrisChou-freeman** [comment]
> That functionality comes from [mini.ai](https://github.com/echasnovski/mini.ai). Create an issue at the plugin's repo, as this can't be fixed here. And I also don't know if this is something inherent with Lua patterns, but I'm sure the plugin's maintainer will give a more appropriate answer.

thanks for quick respond sadly his repo not accept any Issue.

**Comment by dpetka2001** [comment]
See this [comment](https://github.com/echasnovski/mini.nvim/issues/671#issuecomment-1911792325) in the issue. My guess is this is something similar. In treesitter textobjects this is captured as a function (probably because of the arrow function), so you can use `vif` to choose everything inside the first parentheses. 

Also, if you want to create an issue, you create it at the [main](https://github.com/echasnovski/mini.nvim) repo. But I've seen other issues like this and it seems to be a limitation with Lua pattern searching (which the plugin uses). It never hurts to try though.
