### ISSUE TITLE
wrong dependency on mini-ai

### ISSUE THREAD

**Issue by lucax88x** [LazyVim/LazyVim#330]
https://github.com/LazyVim/LazyVim/blob/befa6c67a4387b0db4f8421d463f5d03f91dc829/lua/lazyvim/plugins/coding.lua#L157

shouldnt this one be
```lua  
dependencies = { "nvim-treesitter/nvim-treesitter-textobjects" }
```

**Comment by dpetka2001** [comment]
Not really because it's already defined in [treesitter](https://github.com/LazyVim/LazyVim/blob/079c685831fd64ab139b8824db54e76b04724346/lua/lazyvim/plugins/treesitter.lua) correctly which loads when a buffer is read, so in `mini-ai` (which is loaded `VeryLazy` and thus after treesitter) it can be referenced with just its name.

**Comment by lucax88x** [comment]
Thanks for the explanation!
