### ISSUE TITLE
feature: Remove Flit

### ISSUE THREAD

**Issue by zim0369** [LazyVim/LazyVim#355]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

I have made little to no customization to my correctly installed lazyvim config. I get this error as soon as a hit `f` after updating my plugins yesterday:
![image](https://user-images.githubusercontent.com/85027668/222087660-547b5cbc-f1c5-49e4-a0c8-2370ed61d294.png)

This likely happens due to the flint plugin.

*I didn't bother investigating the error because I prefer disabling the plugin instead*

### Describe the solution you'd like

I think the flint plugin is unnecessary as we have leap which can activated by just hitting `s`/`S`.
For inline motions vim's `f`/`t`/`F`/`T` are faster. If we need a little extra then leap is there to help.

### Describe alternatives you've considered

Leap

**Comment by dpetka2001** [comment]
Have you tried [this](https://www.lazyvim.org/configuration/plugins#-disabling-plugins)?

**Comment by folke** [comment]
Upstream changes to leap broke flit https://github.com/ggandor/leap.nvim/issues/114

I just pushed a LazyVim change to pin to the last working leap commit, so if you update, flit should be working again

**Comment by ggandor** [comment]
As a side note, I would actually support this - flit is just a hack of sorts, without any stability guarantees, so it cringes me a little bit to see it bundled in such a huge(ly popular) project.

> For inline motions vim's f/t/F/T are faster

I don't understand this, Flit is _exactly_ as fast as vim's native motions, it just adds stuff on top of that :)

**Comment by folke** [comment]
@ggandor I mainly use flit for multiline f/F/...

Based on your comment, it's probably best that we switch to use https://github.com/echasnovski/mini.nvim/blob/main/readmes/mini-jump.md instead then?

**Comment by ggandor** [comment]
@folke 
Well, let's think about it. There is no perfect solution on my side:

1) Merging Flit to Leap would 1. make Leap's code a big if-else mess 2. hurt the conceptual integrity of Leap (one way to do things, no thinking/weighing). This is why f/t motions were not included in the first place.

2) Reimplement even more parts of Leap in Flit. (Brr...)

3) Status quo, with synchronization problems like this. 

Counterargument to maintaining Flit: the thing is, building such a plugin _on top of_ Leap only makes sense if you want labels, but personally I don't think that is a good idea if someone uses Leap too (for reasons mentioned in 1). Nevertheless I implemented it, because apparently some people do (or use flit without leap), and for the sake of experimenting.

However, for a "simple" clever-f plugin, the minimal requirements for me would be:

- "caterpillar" highlighting of leap/flit (configurable limit, only highlights n matches in the given direction; at the n-1-th match, switch); that is a much better solution than the timeout feature of mini-jump (no matter how you configure it, it will either appear too early or too late, very annoying)

- relative repeat (`f` always repeats forwards, `F` always repeats backwards)

- if `;` is overridden, `,` should work too (needless to say)

Nothing that echasnovski couldn't implement of course.

Counterargument to the counterargument: since Leap is a given, it makes sense to have consistency, the same interface with the exact same behaviour and configuration possibilities.

**Comment by folke** [comment]
I used to use mini.jump, but swicthed to flit mainly to your last point, for consistency on how it looked.

I kinda liked the idea that leap could be an API to be used by other plugins like the AST one you created a while ago. I used it for some time, but had to switch back eventually to treehopper. I read that issue you posted there. Would indeed be cool if treehopper could possibly use leap under the hood.

Flit has been stable for as long as I've been using it. Never had any problems with it, so that's why I didn't see any problems including it in LazyVim. It does what it has to do and builds on top of leap, which is great.

I think I'll keep flit for now, but will add an option (extras) for users to use mini.jump if they rather use that.

**Comment by ggandor** [comment]
> I kinda liked the idea that leap could be an API to be used by other plugins

The specific problem with flit is that there's too big an overlap to implement it by feeding targets to Leap (as it is done now) - either way, things will become ugly. I'm thinking about how this feature could be integrated in a more elegant way, while keeping flexibility.

> I think I'll keep flit for now, but will add an option (extras) for users to use mini.jump if they rather use that.

Yeah, sure, let's leave it at that then, with me tring to be extra careful in the future :)
