### ISSUE TITLE
bug: refactoring.nvim selector issue when using Fzf-lua

### ISSUE THREAD

**Issue by Redoxahmii** [LazyVim/LazyVim#3762]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10

### Operating system/version

Arch Linux

### Describe the bug

`E5108: Error executing lua: ...azyVim/lua/lazyvim/plugins/extras/editor/refactoring.lua:14: module 'telescope' 
 ' not found: `

When you visually select and use `<leader>rs` for Refactor it gives this error when using with Fzf-lua

### Steps To Reproduce

1. Visual Select
2. press `<leader>rs`

### Expected Behavior

Should have alternative to work with Fzf-lua.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  { "LazyVim/LazyVim", import = "lazyvim.plugins" },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
@Redoxahmii 

I tried something, but not sure how well it works and since I don't use `refactoring.nvim`, I thought maybe you'd give it a go. Do the following
```lua
-- ~/.config/nvim/lua/plugins/core.lua
return {
  {
    "dpetka2001/LazyVim",
    branch = "fix/refactoring-pick",
  },
}
```
Then open Lazy UI by pressing `<leader>l` and then press `C` (check for updates) and `U` (do the updates). Then restart Neovim and test out the behavior of `refactoring.nvim` with fzf-lua. 

If there's something not working, please do let me know so I don't do a PR and leave it to the maintainer to come up with a proper fix.

**Comment by Redoxahmii** [comment]
Yes it seems to be working now.
