### ISSUE TITLE
bug: noice causes UI bug when using neovim via ssh

### ISSUE THREAD

**Issue by benjaminbauer** [LazyVim/LazyVim#3896]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.0

### Operating system/version

Linux container on MacOs

### Describe the bug

When using LazyVim in an ssh session, the first line of the lsp hover menu is not properly indented
<img width="750" alt="image" src="https://github.com/LazyVim/LazyVim/assets/1436222/0e9cae2e-09fe-4f03-be97-7c9ee230d4b7">

This leads to an incomplete redraw when leaving hover:
<img width="750" alt="image" src="https://github.com/LazyVim/LazyVim/assets/1436222/769c760f-4d5f-4cad-8b3b-f5cf24df5728">

This does not happen:
- when outside of ssh
- or with with noice disabled

I could not reproduce it outside of LazyVim (just lua lsp and noice). So I assume it is caused in combination with another setting/plugin in LazyVim

### Steps To Reproduce

1. ssh into a server with LazyVim setup
2. `nvim -u repro.lua repro.lua`
3. `lua vim.lsp.buf.hover()` on a word that has some docs
4. navigate one line up

I could reproduce this in different Terminal Emulators (Alacritty, Mac Termin, iTerm2)

### Expected Behavior

Should behave as it does outside of ssh

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  { "LazyVim/LazyVim", import = "lazyvim.plugins" },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
Not a Noice issue. At most a Neovim issue or a problem with your muxer/terminal

**Comment by benjaminbauer** [comment]
If I disable noice, it does not appear

**Comment by folke** [comment]
So? Then disable noice. Still **not** a noice issue...

**Comment by folke** [comment]
I'm not responsible for every bug that might be triggered by your environment.
Neither is cmp in this case.

It's a Neovim bug, or a bug with your terminal...

**Comment by folke** [comment]
Wrong termcap being passed through possibly

**Comment by thebitwise** [comment]
Just adding a comment here for anybody else running into this issue in some form, @folke is correct this is not a LazyVim, noice, or other plugin related bug. I also came here first looking for information because I was having trouble tracking down my issue. I realize this comment is going to be rather specific to my own setup but perhaps for anyone else encountering a similar issue this can point them in another investigative direction.

For context: I'm using LazyVim/Neovim inside of Devpods in order to utilize devcontainers through SSH and have been seeing this issue for a few weeks now. If I utilize SSH alone through some custom SSH configuration then I cannot reproduce this issue, everything behaves as expected. The issue is also not present if I use docker exec as an entry into the container as opposed to SSH. The issue for this particular setup appears to be related to this issue with Devpods (for my scenario): [https://github.com/loft-sh/devpod/issues/1187](url)

**Comment by benjaminbauer** [comment]
That is exactly my problem. Just adding a working link here https://github.com/loft-sh/devpod/issues/1187
