### ISSUE TITLE
bug: relative line numbers doesnt work

### ISSUE THREAD

**Issue by hxsggsz** [LazyVim/LazyVim#3934]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.11.0

### Operating system/version

ubuntu 24.04

### Describe the bug

my relative line numbers doesnt work, I have added the 
```lua
vim.opt.number = true
vim.opt.relativenumber = true
```

to my options.lua file and it still doesnt work, I don´t know why and how it doesnt toggle with the command but with the repro.lua file this doesnt work, someone have some idea about why this happen?

![image](https://github.com/LazyVim/LazyVim/assets/103784814/964d64ba-5820-40fa-bce7-87890f51e4a2)

### Steps To Reproduce

1. press <leader>uL to disable relative line numbers
2. press <leader>uL again  to enable relative line numbers
3. it dont work

### Expected Behavior

to toggle the relative line numbers

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  { "LazyVim/LazyVim", import = "lazyvim.plugins" },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
Probably using an old version of nightly? Try updating and see if that solves your problem. For me it's working fine on today's nightly version.

**Comment by troycomi** [comment]
I'm seeing the same bug, using lazy.nvim 077102c and LazyVim 12818a6.
They are both following the main branch but seem to be the most recent versions.
If not, can you walk through how to use the nightly releases?
Thanks, awesome project!

**Comment by dpetka2001** [comment]
You're not mentioning the Neovim version. What does `nvim -v` show?

**Comment by troycomi** [comment]
```
NVIM v0.11.0-dev-85+g93c55c238
Build type: RelWithDebInfo
LuaJIT 2.1.1713484068
```

**Comment by dpetka2001** [comment]
This is a very old version of Neovim nightly from May 25 2024. Update Neovim to latest nightly. Unfortunately, this is the problem with having Neovim nightly installed. You have to regularly update to keep with latest changes or use Neovim stable as an alternative.

**Comment by troycomi** [comment]
I'm using snap to install nvim (and I was hoping keep up to date).  Do you recommend using the latest appimage or something different?  Thanks for the help!

**Comment by dpetka2001** [comment]
I'm personally using [bob](https://github.com/MordechaiHadad/bob) to install Neovim. You can choose very easily different versions of Neovim to install and also switch between them with just a command (e.g `bob use nightly` or `bob use stable`). But that's just a personal preference. I've also read in the past that snap versions of Neovim tend to show some weird behavior regarding `nvim-treesitter` and its parsers (however that may have been fixed since I last searched about it and may not be true anymore).

**Comment by ctaymor** [comment]
I'm seeing this issue as well
When I put the options in `lua/config/options.lua`, it doesn't work. This is confusing because [the docs suggest that setting number to true is the default](https://www.lazyvim.org/configuration/general#options)
```lua
vim.opt.number = true
```

However, if I put that same config in`lua/config/lazy.lua` instead, it picks up that configuration and sets the number properly.

I'm using the latest nvim from homebrew:
```bash
$ nvim -v
NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1720049189
```

**Comment by ctaymor** [comment]
Hi @dpetka2001 , thanks. I did not use the LazyVim starter to install lazyvim. I followed a friend's tutorial, but looking back at it, I have no idea why I didn't use the starter. 
Actually, looking at this, I'm realizing that that is because I'm using LazyNvim but not LazyVim. Which has totally different installation instructions. Sorry I missed that I was in the wrong repo

**Comment by dpetka2001** [comment]
[lazy.nvim](https://github.com/folke/lazy.nvim) is just a Neovim package manager used to install plugins. LazyVim is a Neovim distro which comes preconfigured with a specific set of plugins and settings. You can use `lazy.nvim` without LazyVim if you like. It's up to you to decide.

**Comment by ctaymor** [comment]
Ok, that makes sense. I don't actually want to use LazyVim, just lazy.nvim and a pared down plugin list. That said, I'm baffled why loading plugins would load the config dir which seems to be missing/not imported. But, thats not really an issue for this repo. Thanks :)
