### ISSUE TITLE
feature: vim.g.lazyvim_disable_git_files

### ISSUE THREAD

**Issue by aguynamedben** [LazyVim/LazyVim#3974]
### Did you check the docs?

- [X] I have read all the LazyVim docs
- [X] This is not a request for a new or existing extra (see above)

### Is your feature request related to a problem? Please describe.

I love LazyVim, this is a humble feature request. If you can't implement it, feel free to close, but I just wanted to convey the experience.

I work on a large monorepo where `git ls-files --exclude-standard --cached --others` takes over 10 seconds to complete and `git status` takes 8.5 seconds to complete.

The default keybindings for many commands are `LazyVim.pick("auto")`. It took me 2 weeks of tweaking LazyVim to understand why <leader><space> was so slow, and why the title in Telescope said "Git Files" even though the which-key helper said "Find Files (Root dir)". I thought this was maybe bug or performance issue with Telescope, so I switched to fzf-lua hearing that it had better performance, and the same thing was happening. I eventually found [this line of buried magic](https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/plugins/extras/editor/fzf.lua#L21), as well as explanations [here](https://github.com/LazyVim/LazyVim/issues/3831#issuecomment-2196321382) and [here](https://github.com/LazyVim/LazyVim/issues/1425)

This was all surprising to me, particularly because the first few days I was using LazyVim I liked that it had <leader>ff for Find Files and <leader>fg for Git Files.

My request is that LazyVim have an option that always uses the normal "files" picker, instead of the dynamic switching between "git_files" and "find_files" for Telescope and lua-fzf. I also think the labeling in which-key could be improved to describe this dynamic behavior. Maybe <leader>ff / <leader><space> should just be "Auto-Find Files" or something.

This would be helpful for people that work on large monorepos. I haven't investigated yet, but on the same large monorepo:
* neo-tree is really slow, I'm not sure if it's using git_files at the LazyVim level, or I just need to dial back it's usage of git. I'm also going to try nvim-tree.
* fzf-lua warns about `git status` being slow and recommends running with `:FzfLua files git_icons=false`

Here's my plugins/fzf-lua.lua

```lua
return {
  { import = "lazyvim.plugins.extras.editor.fzf" },

  {
    "ibhagwan/fzf-lua",
    opts = {
      defaults = {
        -- This is slow on large git projects
        git_icons = false,
      },
    },
    keys = {
      -- LazyVim has a "picker" scheme where if LazyVim.pick("auto") is set, and
      -- you're in a git project, the LazyVim "picker" will use the `git files`
      -- command to list files. This is slow on large git projects, so override
      -- default LazyVim bindings for commands that do this.
      -- https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/util/pick.lua#L75
      { "<leader><space>", LazyVim.pick("files"), desc = "Find Files (Root Dir)" },
      { "<leader>ff", LazyVim.pick("files"), desc = "Find Files (Root Dir)" },
      { "<leader>fF", LazyVim.pick("files", { root = false }), desc = "Find Files (cwd)" },
    },
  },
}
```

and here's my config/options.lua

```lua
-- Options are automatically loaded before lazy.nvim startup
-- Default options that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/options.lua
-- Add any additional options here

-- We're using the fzf LazyVim extra, but not via LazyExtras, so we need to
-- turn this on here
vim.g.lazyvim_picker = "fzf"
```

I'd like to add:

```lua
vim.g.lazyvim_disable_git_files = true
```

### Describe the solution you'd like

`vim.g.lazyvim_disable_git_files` in config/options.lua would disable magic usage of `git ls-files`

### Describe alternatives you've considered

Changing keybindings from `LazyVim.pick("auto")` to "LazyVim.pick("files")`, but this took two weeks to figure out as a new user to LazyVim. This is more about not being surprising.

### Additional context

Changing the keymaps is fine now that I know the gotcha, but this was just a really confusing experience as a new user. Thanks for the work you put into LazyVim, it's awesome!

**Comment by dpetka2001** [comment]
@aguynamedben My idea would be to change the default keymaps `<leader>ff/fF` to use `LazyVim.pick("files")` and only have `<leader>space` for `LazyVim.pick("auto")`. Would that be acceptable instead of using a `vim.g.lazyvim_disable_git_files` to determine the behavior of auto-picker? Of course it would also be necessary to change the keymap description of `<leader>space` to something that differentiates the 2 behaviors like you already suggested.

Regarding `neo-tree`, it uses the source `git-status` by default, so that must probably be the cause of the lag you observe with it as well. This is enabled by default `neo-tree` configuration (I just checked with a simple `lazy.nvim` and `neotree` configuration without having LazyVim installed), so you might want to disable it in your personal configuration.

@folke Would you be interested in such a change? Or would you prefer another approach?

**Comment by folke** [comment]
I always completely forget why I ever changed it so that it switches between the two .
There's an important reason though. Need to check that again :)

Otherwise it would of course be best to always use `files`.

Had it something to do that `files` doesn't show exactly the same files as `git files`? Like dot/hidden files that are under source control, but not shown?

I just checked with fzf lua and there the list is exactly the same.

**Comment by folke** [comment]
In the LazyVim repo:
- Telescope:
  - auto: 164
  - files: 148
  - git: 160
 - fzf-lua:
   - auto: 164
   - files: 164
   - git: 160

**Comment by dpetka2001** [comment]
Then probably the `show_untracked` option in telescope, which i've seen in other issues as well, which by default is false if i'm not mistaken?

**Comment by folke** [comment]
That's only for git_files.
I'm also looking into it.
Better would be to have auto always use `fd` like with `fzf` but then with the correct options.

**Comment by folke** [comment]
Or just set better defaults for telescope and then we no longer need auto mode

**Comment by folke** [comment]
This seems the correct command:

```sh
fd -t file -H -E .git
```

**Comment by aguynamedben** [comment]
Incredible! Thanks for at least listening to the feedback. And even better to make the defaults better. That was the issue—default was surprising to me as LazyVim/nvim n00b. Nice!
