### ISSUE TITLE
feature: use which-keys new dynamic `desc` and `icon` for the ui toggles

### ISSUE THREAD

**Issue by folke** [LazyVim/LazyVim#4025]
### Did you check the docs?

- [X] I have read all the LazyVim docs
- [X] This is not a request for a new or existing extra (see above)

### Is your feature request related to a problem? Please describe.

Nope

### Describe the solution you'd like

Which-key now has support for dynamic `desc` and `icons`, so we can show better descriptions and icons based on the current state of an option.

Ideally, a function should be added to `util.toggle` that adds these dynamic mappings to which-key with the correct icon that represents the state and a descripion like `show line numbers` & `hide line numbers`.

### Describe alternatives you've considered

Keep the current static keymaps

**Comment by dpetka2001** [comment]
So, @folke, I tried to do something, but unfortunately have hit a wall. How would we be able to set the initial state of the `desc` field dynamically? 

[Here](https://github.com/LazyVim/LazyVim/compare/main...dpetka2001:LazyVim:feat/toggle-desc-icon) you can see my first initial attempt. I've only implemented `<leader>ul` and `<leader>uL` for now. The problem is that when starting Neovim when you first press `<leader>u`, the `which-key` menu will show the initial `desc` from the `keymaps.lua` file. I tried to change in that file the `desc` from the string that it is to `desc = LazyVim.toggle.which_key("relativenumber")`, but it always results to the [condition here](https://github.com/LazyVim/LazyVim/compare/main...dpetka2001:LazyVim:feat/toggle-desc-icon#diff-f993ee1f061afc25eb0ba136aea2e501093a1eb58bf763dfe29e68dc73ab186cR42-R44), because I'm guessing that during the parsing phase `vim.opt_local[option]:get()` always returns false. 

After you press the keymaps, it shows correctly the `desc` and `icon` in which-key menu, no matter how many times you repeat the process. It's only the initial state of `desc` that I'm having trouble with showing the correct description.

If you could give some advice on how to tackle this, I'd really appreciate it. Or maybe this approach is entirely wrong and you can come up with something better.

**Comment by folke** [comment]
Yeah, I need to think about the best way to do this. Will also try to put something together.
