### ISSUE TITLE
bug: "fzf project " does not set pwd to the project path, which is different with what "telescope project" do.

### ISSUE THREAD

**Issue by liuyangzys** [LazyVim/LazyVim#4041]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.0

### Operating system/version

windows 11

### Describe the bug

"fzf project " does not set pwd to the project path

### Steps To Reproduce

1. use "fzf project" to open a file in the selected project
2. check pwd value, or test "leader gs" key map or any thing depends on pwd

### Expected Behavior

the pwd should be set to the project path

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- add any other plugins here
  },
})
```

**Comment by dpetka2001** [comment]
I don't think that's supported, because the plugin only provides a Telescope extension. The compatibility with fzf-lua was done by a user contributor here. There's a keymap `<c-w>` however that I believe does what you want. If you want it to happen automatically like with the Telescope extension you should open a feature request at the plugin's repo to support `fzf-lua` out of the box.

**Comment by dpetka2001** [comment]
Actually the code in `<ctrl-w>` could also be moved to the `default` action for that to happen automatically, but I don't know if all users would like that, because the default LazyVim behavior for `project.nvim` is set to `manual = true`. I believe that's why there's a keymap for changing project directory to stay close with default LazyVim behavior.
