### ISSUE TITLE
bug: news is never considered "read"

### ISSUE THREAD

**Issue by redbeardymcgee** [LazyVim/LazyVim#4149]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.0

### Operating system/version

linux

### Describe the bug

The news popup occurs every time i open neovim, whether it's directly to a file, directory or just plain `nvim` with no args. I've read the news (6 times or so now) and would like lazyvim to acknowledge the fact that there is no new news and i read the old news, so please stop stealing my keyboard inputs on launch.

### Steps To Reproduce

launch neovim

### Expected Behavior

Popup news when there is new news. Disregard news if I have already seen the news. Don't pop up anymore.

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- add any other plugins here
  },
})
```

**Comment by folke** [comment]
I'll need a little bit more info than that, because obviously this is working.

What's the contents of `~/.config/nvim/lazyvim.json`

Is anything special about your system? What OS?

Do you see any errors?

When the news file is open, what does `1<C-G>` show as filename?

And then `:vim.uv.fs_stat(that_FILE)`?

**Comment by redbeardymcgee** [comment]
How can I just disable the news instead?

**Comment by redbeardymcgee** [comment]
I deleted the news entry from lazyvim.json and added `news = { lazyvim = false, neovim = false, },`.

The bug, now that I see what causes it, is that this is not configuration but state. As such, IMO, it should be managed somewhere in `~/.local/state/nvim/lazy/`instead of `lazyvim.json`. Would you consider this change?

**Comment by friend0** [comment]
I'm using nix flakes and home manager to manage my macOS config. Lazyvim configurations alone don't seem to stop the news from popping up for me. The news file `~/.local/share/lzvim/lazy/LazyVim/NEWS.md`.

I believe that json file @redbeardymcgee is referencing is read only for my setup. Since it is stateful WRT news, it always shows up. 
Deleting the file solves the issue. Subscribed for updates. @folke you're my 🐐
