### ISSUE TITLE
feature: add extends/overrides option for changing plugin's default values

### ISSUE THREAD

**Issue by franroa** [LazyVim/LazyVim#4211]
### Did you check the docs?

- [X] I have read all the LazyVim docs
- [X] This is not a request for a new or existing extra (see above)

### Is your feature request related to a problem? Please describe.

Sometimes I want to extend the configuration of a plugin and I silently override the default values. 
It would be nice to have a check (maybe in the plugin manager) that proves if the user really wants to override or to extend.

### Describe the solution you'd like

In the plugin's config, I would put something like this:

```
{
  "neovim/nvim-lspconfig",
  extends: {
    ["my.opt.vtsls"]: 
      {
        name = "@angular/language-server",
        location = LazyVim.get_pkg_path("angular-language-server", "/node_modules/@angular/language-server"),
        enableForWorkspaceTypeScriptVersions = false,
      }
  end,
}
```

Instead of doing it in the opts.

Or maybe, we can still change things in the opts and just pass an override=false for the properties that should not be overriden, and throw an error in case that the options are overriden unintentionally.

### Describe alternatives you've considered

The only thing I could think of is what I out above

**Comment by dpetka2001** [comment]
This is entirely dependent on the `lazy.nvim` plugin manager and has nothing to do with LazyVim distro. You can still extend the default `opts` either with a simple table in your personal configuration (because `opts` get merged in the end into a final plugin spec) or with an `opts` function. For more details you should read the [docs of lazy.nvim](https://lazy.folke.io/).
