### ISSUE TITLE
feature: make dependecy on mason-registry totally optional

### ISSUE THREAD

**Issue by sjcobb2022** [LazyVim/LazyVim#4223]
### Did you check the docs?

- [X] I have read all the LazyVim docs
- [X] This is not a request for a new or existing extra (see above)

### Is your feature request related to a problem? Please describe.

This is not really a problem, more a solution for those who are running lazyvim without mason (for whatever reason). I for one am using NixOS which makes mason unusable (for a lot of cases).

### Describe the solution you'd like

I think mason is an brilliant piece of software, in fact I have contributed binaries to it. However it does have it's downfalls and it's critiques. Whilst I know the packages _are_ well maintained and well secured. Any supply chain attack could affect it at any time.

Therefore, I would like to propose making LazyVim (including extras) agnostic of mason. I know an effort to do so has already been made, but I think further refining is required.

For example, the PHP extra package is dependent on mason-registry for the php-debug-adapter dependency. If mason is not in the path, this fails with and notifies the user every time nvim is loaded.

The same is true for the java extra.

### Describe alternatives you've considered

In my case, using nix-ld to ensure that programs are linked properly on NixOS would solve my problem, however, the previously mentioned aversions to mason are still valid.

**Comment by dpetka2001** [comment]
>  Any supply chain attack could affect it at any time

> the previously mentioned aversions to mason are still valid

These 2 are basically the same and it applies to all software being distributed via `pip` or `npm` that Mason uses under the hood as providers to install the packages. So, I'm not really sure what you're trying to say here. 

Regarding the NixOS part, that's something OS specific and should be handled by the users themselves in my personal opinion, since most Linux distros don't have this problem. 

Since LazyVim uses Mason to install LSP servers, debuggers and other packages, I'm not sure how it could be made Mason agnostic. Except if you mean to remove Mason as a whole from LazyVim, which in my humble opinion seems quite unlikely to happen at least until some other alternative can replace it in its entirety.

**Comment by sjcobb2022** [comment]
> These 2 are basically the same and it applies to all software being distributed via pip or npm that Mason uses under the hood as providers to install the packages. So, I'm not really sure what you're trying to say here.

Mason also installs binaries, that is my issue.


LazyVim can, and is used without mason. It can be disabled very easily. 

I believe there is already precedence for this with: https://github.com/LazyVim/LazyVim/issues/445

**Comment by dpetka2001** [comment]
The precedence from the issue you linked is about being able to disable Mason for people who don't want it, not make Lazyvim agnostic to Mason. These are 2 different things. 

You can install lsp-servers with your package manager and not mason. You just have to set `mason=false` in `nvim-lspconfig`. The same can be done for debuggers etc. But the users themselves have to change the default configuration to take into consideration the new paths in their system. Because like it or not Lazyvim uses Mason for these things by default and that's why it also uses `mason-registry` to figure out the install path on the system. What would be your alternative for figurimg out the install paths in both systems that use Mason and systems that don't (assumming that the solution won't incur big maintenance load and even then I personally would be hesitant to introduce such a change because it will set unnecessary presedence for other potential requests in the future depending on different OS that users use). 

So just disable Mason and configure the install paths yourself.

Please bear in mind i'm just a simple user like you and have no say in this project. I'm just expressing my personal opinion. The maintainer has the final say and will surely look into it when he gets back.

**Comment by sjcobb2022** [comment]
Sure, but if an extra is causing errors because mason isn't installed. Something should be changed about that.

**Comment by dpetka2001** [comment]
You know you can just copy paste the whole Extra that you want into `~/.config/nvim/lua/plugins/extras` and just change the parts that you want, like install paths for debuggers and what not, and `LazyExtras` will pick it up. Then you just enable your own custom Extra and not the LazyVim default.

> Sure, but if an extra is causing errors because mason isn't installed. Something should be changed about that.

It's only causing errors for you because you don't want to use an integral part of LazyVim that it's built around, namely Mason. Because Mason is in fact an integral part of LazyVim for installing LSP servers, debuggers and what not and makes it easier to maintain. Basically you're suggesting that LazyVim should not be built around Mason. But how would you then get the install paths of the packages being used in the LazyVim configuration? There could be various ways of installing the packages and you can't ensure a uniform installation path for all the packages. Mason just provides that and that's why most distros use it. Because it makes maintenance load easier.
