### ISSUE TITLE
feature: options to disable flit.nvim when recording a macro

### ISSUE THREAD

**Issue by GreenSleeper** [LazyVim/LazyVim#424]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

`LazyVim` uses `flit.nvim` to enchance the `f` `t` command by labeling mutiple matches to jump to. But when I'm recording a macro, if I use `f` or `t` command in the macro, sometimes it will mess up the macro behavior and jump to somewhere i didn't intend to. For example, I records a macro of `f,h`, meaning find next `,` and move one character left, then i apply this macro to multiple lines. But if these is a label `h` existing after `f,`, the `h` will jump to it, making the macro totally unpredictable.

### Describe the solution you'd like

An option can be provided that `flit.nvim` can be auto closed when recording macro.

### Describe alternatives you've considered

I can just disable `flit.nvim` in my configuration.

### Additional context

Not sure whether should I post it here or the `flit.nvim` repository, I'll just put it here first.

**Comment by folke** [comment]
not a lazyvim issue

**Comment by GreenSleeper** [comment]
Sure, amazing work BTW, thanks a lot.

**Comment by davetrust** [comment]
> not a lazyvim issue

You can still help point someone in the right direction.

As wonderful as LazyVim is, you have a fair number of people who use it and wonder why _basic_ Vim/Neovim functionality is affected out-of-the-box. And when we go looking for information on this, a lot of the Github issue threads we get pointed at have this flippant tone to them. It's really odd to get a more helpful tone on Reddit than on Github.

As @GreenSleeper pointed out, you've done great work here. But it seems that you personally don't use every single feature Vim/Neovim offers natively and so unintentionally you've remapped or pulled in thirdparty plugins that have mapped over that functionality. If you were personally using a lot of these features, I think you would have noticed the overlap.

So instead we're the one noticing it and because you're often dismissive about this stuff, we've having to help each other out on Reddit instead of you just letting us help you improve the docs, examples, and wikis here (which would be better).

**Comment by davetrust** [comment]
> ### Did you check the docs?
> 
>     * [x]  I have read all the LazyVim docs
> 
> 
> ### Is your feature request related to a problem? Please describe.
> 
> `LazyVim` uses `flit.nvim` to enchance the `f` `t` command by labeling mutiple matches to jump to. But when I'm recording a macro, if I use `f` or `t` command in the macro, sometimes it will mess up the macro behavior and jump to somewhere i didn't intend to. For example, I records a macro of `f,h`, meaning find next `,` and move one character left, then i apply this macro to multiple lines. But if these is a label `h` existing after `f,`, the `h` will jump to it, making the macro totally unpredictable.
> ### Describe the solution you'd like
> 
> An option can be provided that `flit.nvim` can be auto closed when recording macro.
> ### Describe alternatives you've considered
> 
> I can just disable `flit.nvim` in my configuration.
> ### Additional context
> 
> Not sure whether should I post it here or the `flit.nvim` repository, I'll just put it here first.

Thanks for filing this issue @GreenSleeper 🙌  . I was trying to figure out what was interfering with macro recording and this does seem to be the culprit.

**Comment by abeldekat** [comment]
@davetrust,

That's your third negative comment:

https://github.com/LazyVim/LazyVim/issues/2066#issuecomment-1879406919

https://github.com/LazyVim/LazyVim/discussions/1227#discussioncomment-8071893

Quoting:

> But it seems that you personally don't use every single feature Vim/Neovim offers natively

--> You are assuming. It's just ridiculous.

> So instead we're the one noticing it

--> There is no `we're`. You are trying to include other people, creating a "we" and "they".

> and because you're often dismissive about this stuff

--> Factual, I would say

And the final one:

> You can still help point someone in the right direction.

@davetrust, nobody owes you anything!

**Comment by davetrust** [comment]
> @davetrust,
> 
> That's your third negative comment:
> 
> [#2066 (comment)](https://github.com/LazyVim/LazyVim/issues/2066#issuecomment-1879406919)
> 
> [#1227 (reply in thread)](https://github.com/LazyVim/LazyVim/discussions/1227#discussioncomment-8071893)
> 
> Quoting:
> 
> > But it seems that you personally don't use every single feature Vim/Neovim offers natively
> 
> --> You are assuming. It's just ridiculous.
> 
> > So instead we're the one noticing it
> 
> --> There is no `we're`. You are trying to include other people, creating a "we" and "they".
> 
> > and because you're often dismissive about this stuff
> 
> --> Factual, I would say
> 
> And the final one:
> 
> > You can still help point someone in the right direction.
> 
> @davetrust, nobody owes you anything!

You're acting like you or the package authors are above criticism. Or perhaps you think that because your work is unpaid, the only kind of feedback that is acceptable are compliments and polite requests for assistance wrapped in compliments. That is unrealistic.

And to your point about "negative" tone, this may be a generational interpretation. It's beyond the scope of Github discussions nonetheless, but put simply, when you force your online interactions to filter out everything but positive tone (ie, compliments), then _neutral_ tone and constructive criticism _feels_ like negative. You are interpreting constructive criticism or observations that are neutral as negative attacks.

I stand by all three of those statements you took issue with. None of those were attacks, none of those were abusive, and all of those were based on the past two weeks of combing through Reddit, Github, and Medium to understand how to use LazyVim and the suite of packages it integrates. And so far I haven't needed to open an issue or create a thread on Reddit because the half dozen or so issues that I've collided with _were filed by someone else on Reddit or Github already_. That means other people encountered something unexpected, went to the docs like I did, and then posted a question to get unstuck.

I've observed the way those questions/issues were handled on Github, and _that_ is why I think constructive criticism is deserved. It doesn't matter if your work is unpaid or not, it doesn't matter if you're doing your best or not. A personal attack isn't desrved, of course, but that's not what happened.

We all work for a living (or is that too much of an assumption?), and just because someone makes a critique doesn't mean they are ungrateful for the work or that they take from open-source without ever giving back.

**Comment by dpetka2001** [comment]
Implying that someone, who you've never interacted with, is patronizing is not an attack, rather constructive criticism? Really?? How can that be seen as constructive criticism? Please do tell.

**Comment by davetrust** [comment]
> Implying that someone, who you've never interacted with, is patronizing is not an attack, rather constructive criticism? Really?? How can that be seen as constructive criticism? Please do tell.

I think you're pulling it out of context. On that thread someone jumped it to improve upon the answer you gave and make it much clearer what to do to resolve the issue. I complimented that they did and and mentioned your comment was a tad patronizing. The two pieces go together

**Comment by dpetka2001** [comment]
How exactly was my comment patronizing? I specifically gave a detailed answer to the user who created the issue about how to solve his problem.

**Comment by abeldekat** [comment]
@davetrust,

Your [answer](https://github.com/LazyVim/LazyVim/issues/424#issuecomment-1890086460) to my [comment](https://github.com/LazyVim/LazyVim/issues/424#issuecomment-1889913908) is adding more of the same to the discussion [**you**](https://github.com/LazyVim/LazyVim/issues/424#issuecomment-1889851421) started, thereby hijacking this issue.

You write:
> We all work for a living (or is that too much of an assumption?), and just because someone makes a critique doesn't mean they are ungrateful for the work or that they take from open-source without ever giving back.

You are being sarcastic here, when writing "too much of an assumption". That line is totally irrelevant and I take offense.

Your [answer](https://github.com/LazyVim/LazyVim/issues/424#issuecomment-1890142201) to [this](https://github.com/LazyVim/LazyVim/issues/424#issuecomment-1890137859) comment, quoting:

> I think you're pulling it out of context. On that thread someone jumped in to improve upon the answer you gave and make it much clearer what to do to resolve the issue. I complimented their effort as helpful and contrasted it against your comment, that it was a tad patronizing. The two pieces go together

In the quote above, you are writing: .... that it was a *tad* patronizing ...
In your [*original*](https://github.com/LazyVim/LazyVim/issues/2066#issuecomment-1879406919) comment, you **don't** write the word `tad`, nor any other adjective before the word *patronizing*:

> Appreciated when someone is helpful and clear and not patronizing to users who are puzzled as to why a tool behaves in an unexpected manner (ie overridding basic Vim motioms that are indeed used frequently)

You were *indirectly* referring to someone totally dedicated to the project when writing that comment. Saying that your comment is being pulled out of context  and adding the word "tad" in your reaction is beyond words to me. I will leave it at that.
