### ISSUE TITLE
bug: Unable to Override Plugin Keymap

### ISSUE THREAD

**Issue by danrasmuson** [LazyVim/LazyVim#4284]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.1 commit c3ae0327c01aab461531bfc0fcdfb4dd3a779205

### Operating system/version

MacOS Sonoma 14.3

### Describe the bug

I am attempting to override the default `<Tab` hotkey assigned to `nvim-cmp` set in LazyVim by  (https://github.com/LazyVim/LazyVim/blob/12818a6cb499456f4903c5d8e68af43753ebc869/lua/lazyvim/plugins/coding.lua#L107)

I have followed the `Adding & Disabling Plugin Keymaps` docs https://www.lazyvim.org/configuration/plugins#%EF%B8%8F-adding--disabling-plugin-keymaps and this code here ~/dots/nvim/lua/plugins/nvim-cmp.lua

```lua
return {
  "nvim-cmp",
  keys = {
    {
      "<Tab>",
      false,
    },
  },
}
```

When I restart nvim and run `verbose map <Tab>` it show that the same hotkey is still assigned to nvim.

```
s  <Tab>       * <Lua 64: ~/.local/share/nvim/lazy/LazyVim/lua/lazyvim/plugins/coding.lua:108>
	Last set from Lua (run Nvim with -V1 for more details)
```

### Steps To Reproduce

1. Add the user setting to disable this keymap

~/dots/nvim/lua/plugins/nvim-cmp.lua

```lua
return {
  "nvim-cmp",
  keys = {
    {
      "<Tab>",
      false,
    },
  },
}
```

2. Restart and confirm that the keymap is not disabled `verbose map <Tab>`

### Expected Behavior

The hotkey ought to be disabled after adding this keymap

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- add any other plugins here
  },
})
```

**Comment by dpetka2001** [comment]
The `<tab>` keymap gets defined in `coding.lua` as you pointed out but for specific modes as can be seen [here](https://github.com/LazyVim/LazyVim/blob/12818a6cb499456f4903c5d8e68af43753ebc869/lua/lazyvim/plugins/coding.lua#L113). So, when you disable it you also have to define the same modes, otherwise `normal` mode is recognized as default. 

It's also mentioned in the [docs here](https://www.lazyvim.org/configuration/plugins#%EF%B8%8F-adding--disabling-plugin-keymaps)
> caution
Make sure to use the exact same mode as the keymap you want to disable. You don't have to specify a mode for normal mode keymaps.

So, to disable it you should do 
```lua
  {
    "hrsh7th/nvim-cmp",
    keys = {
      { "<Tab>", mode = { "i", "s" }, false },
    },
  },
```

**Comment by danrasmuson** [comment]
@dpetka2001. Perfect! thank you for the help!
