### ISSUE TITLE
bug: macros double paste

### ISSUE THREAD

**Issue by hesxenon** [LazyVim/LazyVim#4286]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.11.0-dev+596-g4e8efe002

### Operating system/version

fedora 40

### Describe the bug

Any macro that uses registers seems to double paste the registers content.

### Context
I think this is also the reason (or related to) for lazyvim not being able to handle macro repetitions well

### Steps To Reproduce

1. run the docker starter for lazyvim
2. write `foobar` and go to normal mode
3. key sequence: `0qqctb<C-r>"<Esc>0q@q`
4. text is now `foofoobar`

### Expected Behavior

Should not change the text as I'm pasting the changed content into the same place, same as regular nvim (ran the same steps with `nvim -u /dev/null`)

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- add any other plugins here
  },
})
```

**Comment by dpetka2001** [comment]
This is related to `which-key` plugin. If you disable it the error does not occur. I also found [this issue](https://github.com/folke/which-key.nvim/issues/822) which seems relevant and also [this one](https://github.com/folke/which-key.nvim/issues/702) that was supposed to be fixed, but apparently it's not in its entirety. 

You should better create an issue at `which-key` github repo or comment at the issues I linked above with details about your problem, since it has to be fixed in the plugin itself and not in LazyVim repo. In the meantime you can disable the `registers` feature in which-key with the following until it gets fixed
```lua
  {
    "folke/which-key.nvim",
    opts = {
      plugins = {
        registers = false,
      },
    },
  },
```

**Comment by hesxenon** [comment]
closing in favor of the referenced issue
