### ISSUE TITLE
bug: Ctrl-N/P doesn't work on buffers

### ISSUE THREAD

**Issue by chiefjester** [LazyVim/LazyVim#4414]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.1

### Operating system/version

Ubuntu 22.04.1 LTS

### Describe the bug

Ctrl-N/P doesn't offer suggestions from other buffers anymore. It does read current buffer, but it doesn't fetch suggestions from other opened buffers

### Steps To Reproduce

1. Make a new File, then type anything, eg, apple
2. type :sp foo.txt
3. Type ap
4. Press Ctrl-N

### Expected Behavior

It should pick up apple on the other buffer as source of completion

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- add any other plugins here
  },
})
```

**Comment by dpetka2001** [comment]
I was able to reproduce this outside of LazyVim with the following `repro.lua`
```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
	spec = {
		{
			"hrsh7th/nvim-cmp",
			dependencies = {
				"hrsh7th/cmp-nvim-lsp",
				"hrsh7th/cmp-buffer",
				"hrsh7th/cmp-path",
			},
			opts = function(_, opts)
				local cmp = require("cmp")
				opts.mapping = cmp.mapping.preset.insert({
					["<C-Space>"] = cmp.mapping.complete(),
				})
				opts.sources = cmp.config.sources({
					{ name = "nvim_lsp" },
					{ name = "path" },
				}, {
					{ name = "buffer" },
				})
			end,
		},
	},
})
```
It seems that something is happening with `cmp.mapping.preset.insert` because as soon as you comment out those 3 lines, then the default `<C-n>` is able to suggest completions from other buffers. I'd suggest you create an issue at `nvim-cmp` repo if you want this resolved, since it doesn't seem to be LazyVim related.

**Comment by dpetka2001** [comment]
In your repro you're not using `cmp.mapping.preset.insert` to set the mappings. That's what's causing the problem.

**Comment by dpetka2001** [comment]
I just tried your repro but instead of
```lua
  mapping = {
    ['<CR>'] = cmp.mapping.confirm({ select = true })
  },
```
the following
```lua
  mapping = cmp.mapping.preset.insert({
    ['<CR>'] = cmp.mapping.confirm({ select = true })
  }),
```
and it doesn't work even with your repro.

**Comment by dpetka2001** [comment]
Ok I believe I found what the issue is.

When users don't use `mapping = cmp.mapping.preset.insert`, then the default Neovim `:h i_CTRL-N` is used and that is returning the same words in other buffers. 

When users are using `mapping = cmp.mapping.preset.insert`, then the default Neovim `i_CTRL-N` stops working because it gets overwritten by `<C-n>` that `nvim-cmp` sets as can be seen [here](https://github.com/hrsh7th/nvim-cmp/blob/ae644feb7b67bf1ce4260c231d1d4300b19c6f30/lua/cmp/config/mapping.lua#L44-L53).

The solution for what you want is to configure the source `buffer` as shown in [these examples](https://github.com/hrsh7th/cmp-buffer?tab=readme-ov-file#get_bufnrs-type-fun-number), so that `nvim-cmp` can get buffer completions from other buffers as well.

So, it's neither a LazyVim bug nor a `nvim-cmp` bug. It's a user configuration issue. LazyVim hasn't configured the buffer source to get completions from other buffers, because it uses its default configuration, which is to only return completions from the current buffer.

> Default: function() return { vim.api.nvim_get_current_buf() } end

**Comment by dpetka2001** [comment]
> I'm not using this, the default LazyVim config doesn't work with buffers, even if I zap all my settings.

I just explained why it doesn't work. It only uses the plugin's default configuration. It's up to the user to configure it further.

> Well, isn't LazyVim supposed to provide sane defaults? If their default doesn't work with buffers, it's a bug? No?

Sane defaults is really up to interpretation and sometimes users also mean personal preferences, which can't be taken 100% into account when configuring a Neovim distro (some will be satisfied, some won't). If something is configurable by the user, then I don't believe it's a bug. It's just a user configuration issue. So, users should just change default settings that they don't find to their own preferences.

Concerning `cmp-buffer` configuration, LazyVim uses its default configuration as it comes. `nvim-cmp` can already be sluggish with certain LSP servers, so making `cmp-buffer` traverse all the buffers and generate completions from other buffers as well could make it feel even more sluggish. In my personal configuration I would only use the example of visible buffers to avoid making `nvim-cmp` more sluggish.

Regarding your code example, you're only inserting another source with `name = "buffer"`, but there's already one from default LazyVim configuration. So, you should first remove the default one and then add your custom with the options that you want, so that there are no conflicts. Something like the following should work
```lua
return {
  {
    "hrsh7th/nvim-cmp",
    opts = function(_, opts)
      opts.sources = vim.tbl_filter(function(source)
        return not vim.tbl_contains({ "buffer" }, source.name)
      end, opts.sources)
      table.insert(opts.sources, {
        name = "buffer",
        index = 2,
        option = {
          get_bufnrs = function()
            return vim.api.nvim_list_bufs()
          end,
        },
      })
    end,
  },
}
```

**Comment by dpetka2001** [comment]
> I'm not using cmp.mapping.preset.insert, is it on LazyVim? 

Yes, LazyVim uses `cmp.mapping.preset.insert` to define the keybindings for `nvim-cmp` as also suggested in their [recommended configuration](https://github.com/hrsh7th/nvim-cmp?tab=readme-ov-file#recommended-configuration). 

Just add `opts.mapping = {}` in the above snippet in your configuration. By the way what you're describing is the builtin Neovim auto-completion, so you might as well just disable `nvim-cmp` if you don't want it. See [disabling plugins in the docs](https://www.lazyvim.org/configuration/plugins#-disabling-plugins) for how to do that.

**Comment by dpetka2001** [comment]
> `opts.mapping = {}` doing this basically I can't even confirm anything from cmp.

I'm sorry, I meant that you should put inside the table whatever mappings you want. Since, you won't be using `cmp.mapping.preset.insert` it won't overwrite the Neovim builtin `i_CTRL-N`.

> It's that when I upgraded to Lazyvim latest version, and stops working. It feels like regression to be honest.

I can't see how this can happen, since that part of code has been not changed since the first commits of LazyVim as can be seen [here](https://github.com/LazyVim/LazyVim/blame/3dbace941ee935c89c73fd774267043d12f57fe2/lua/lazyvim/plugins/coding.lua#L33-L36). And `cmp-buffer` has always been returning only results from current buffer only [since 3 years ago](https://github.com/hrsh7th/cmp-buffer/blame/3022dbc9166796b644a841a02de8dd1cc1d311fa/lua/cmp_buffer/source.lua#L15-L17). A recent LazyVim upgrade did not change any of these. The only thing that might have changed is how the default Neovim auto-completion works, which this happens on Neovim upstream and LazyVim doesn't configure anything about that. 

So, it's really hard for me to see any regression about what you're describing, since it's been behaving like this since the beginning of LazyVim.

**Comment by dpetka2001** [comment]
So, I was trying to understand the differences between the mappings you mentioned and the default that `nvim-cmp` uses. 

The ones you mention use `cmp.mapping.select_next_item`, which actually checks if `cmp.select_next_item` exists and if it doesn't then it uses `fallback()`, which I'm guessing is the default Neovim builtin `i_CTRL-N` behavior.

The ones being used by default however is `cmp.select_next_item`, which checks if the `cmp` menu is visible and then selects the next item. Otherwise it checks if `pumvisible` is true and uses the default Neovim builtin `i_CTRL-N` behavior for completions or if that is not true then it returns `false` by default. The thing is that in txt files when you use `<C-n>` it complains about `omnifunc` not being set. Whereas in Lua files `omnifunc` is set by `vim.lsp` itself. That is what's causing this mapping to not return anything in txt files. If you try in a Lua file, then even without you adding the mappings you mentioned, it should work like you expect.

It's a subtle difference between the 2 `nvim-cmp` mappings and I didn't even know they were different until I looked at them today. The main difference is that the one you mention uses `fallback` for Neovim builtin `i_CTRL-N`, whereas the default that `nvim-cmp` uses doesn't use `fallback` and if the 2 conditions are not met then it simply returns `false`.

If you like make a PR to add these mappings back in and the maintainer will decide.
