### ISSUE TITLE
bug: Flash search markers have zero contrast on `tokyonight-day`

### ISSUE THREAD

**Issue by Ruben-Kruepper** [LazyVim/LazyVim#4507]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.1 Build type: Release LuaJIT 2.1.1725453128

### Operating system/version

MacOS 15.0

### Describe the bug

The `flash.nvim` jump markers are not legible (almost zero contrast) in the `tokyonight-day` theme.

<img width="625" alt="image" src="https://github.com/user-attachments/assets/e6b98f99-f8b6-48f2-ae15-e07092de348e">

I'm not sure whether this is an issue with the theme or `flash`, but since both are bundled by LazyVim, I figured I'd cry about it here. 🤓 

### Steps To Reproduce

Use flash search via your preferred key binding (`A-s or toggle during search`) with the `tokyonight-day` colorscheme active.

### Expected Behavior

I expected the markers to have **some** contrast so you can actually read them.

### Repro

```lua
Vanilla LazyVim
```

**Comment by dpetka2001** [comment]
I don't really see how this is a bug. Colors are purely personal preferences. `flash.nvim` mentions which highlight groups it uses [here](https://github.com/folke/flash.nvim?tab=readme-ov-file#-highlights) and `tokyonight.nvim` describes how to override default colors and highlight groups [here](https://github.com/folke/tokyonight.nvim?tab=readme-ov-file#-overriding-colors--highlight-groups). 

Just change them to whatever you like.

**Comment by Ruben-Kruepper** [comment]
Thank you for pointing me that way.

I agree that they are purely personal preference, up to the point where you have insufficient contrast to be able to read text.

Since I'm not a maintainer of anything here I'm not going to tell you what is in-scope or out-of-scope, I'm just happy LazyVim exists. 

But I will argue that since **everyone** who uses the default-configuration has this issue, I think it is in scope of this project.

`TODO.nvim` used to have a similar issue with `tokyonight-day`, and somewhere it got fixed kindly enough.

**Comment by dpetka2001** [comment]
I'm just a simple user like you. I'm also not here to tell you what is in-scope or out-of-scope. I'm just expressing my personal opinion. 

To my eyes I can perfectly discern the `FlashLabel` even in `day` variant. That is not to say that I'm doubting you have trouble doing so. It's just to say, like I've already said, that colors are personal preferences based on how your eyes can perceive them. That's why I expressed my opinion that I don't believe this is a LazyVim bug. I've also changed for example the `Gitsigns` highlight groups to fit more my personal preferences, that's why I suggested you do the same for the `FlashLabel` that you have trouble with.

The maintainer of the project is the same as `tokyonight`, but if I were to make a FR to change a default highlight group for `tokyonight`, I would make it in the plugin's repo. That's all.

I'm just trying to be as helpful as I can for users in this project, so I sincerely hope I didn't come across as somewhat offensive. That was not my intention.
