### ISSUE TITLE
feature(blink): add support for AI completion extras

### ISSUE THREAD

**Issue by folke** [LazyVim/LazyVim#4702]
### Did you check the docs?

- [x] I have read all the LazyVim docs
- [x] This is not a request for a new or existing extra (see above)

### Is your feature request related to a problem? Please describe.

Right now, only the copilot extra has been updated to work with blink.

With blink, we no longer show AI suggestions as completions, since I couldn't get that to work with `blink-compat`, but we use `<tab>` to accept a suggestion.

### Describe the solution you'd like

Implement a similar approach for the other AI extras.

### Describe alternatives you've considered

none

**Comment by Conarius** [comment]
There's also blink-cmp-compat afaik to make everything for nvim-cmp compatible with blink, so you can replace nvim-cmp with blink entirely.

**Comment by OneOfOne** [comment]
I can confirm it's not working for copilot, only thing keeping me from switching.

**Comment by dpetka2001** [comment]
@folke I tried to implement for `codeium.nvim` but couldn't make it work. I did
```lua
      keymap = {
        ["<Tab>"] = {
          function(cmp)
            if cmp.is_in_snippet() then
              return cmp.accept()
            elseif require("codeium.virtual_text").get_current_completion_item() then
              LazyVim.create_undo()
              require("codeium.virtual_text").accept()
              return true
            else
              return cmp.select_and_accept()
            end
          end,
          "snippet_forward",
          "fallback",
        },
      },
```
but it doesn't complete anything. I added a `print` just after `LazyVim.create_undo` and it gets printed. So, the condition about a completion item existing is true. I even cloned `codeium.nvim` and added a `print` inside `codeium.virtual_text.accept()` and that gets printed as well (so the function gets called) but I can't exactly understand why it's not working. I'm not familiar with either codebase and my lack of knowledge makes it harder for me to understand.

On the other hand if I add a keymap into `keymaps.lua` like the following
```lua
vim.keymap.set("i", "<Tab>", function()
  return require("codeium.virtual_text").accept()
end, { silent = true, expr = true, nowait = true })
```
It works correctly. I also tried the same in `keys` section of the plugin and works correctly there as well.

It must have to do with how `blink.cmp` is setting up the mappings and maybe what the `codeium.virtual_text.accept()` function returns that doesn't make `blink` happy?? Unfortunately, I don't know what to do to proceed. Is `blink.cmp` adding the mappings with `expr = true`? Because if I remove `expr = true` from the mapping in `keymaps.lua`, then that doesn't work as well (but [here](https://github.com/Saghen/blink.cmp/blob/973f06a164835b74247f46b3c5b2ae895a1acb1b/lua/blink/cmp/keymap.lua#L247-L251) it seems that it sets `expr = true`).

I even tried to not lazy-load `blink.cmp` because of [this](https://github.com/Saghen/blink.cmp/blob/973f06a164835b74247f46b3c5b2ae895a1acb1b/lua/blink/cmp/keymap.lua#L117-L121), in case maybe the mappings were not applied correctly, but I got the same behavior.

**Comment by folke** [comment]
What if you do `return require("codeium.virtual_text").accept()` instead?

**Comment by dpetka2001** [comment]
I tried that as well and commented out `return true` but got the same behavior. I just pasted this here as it was in the example of copilot but I've tried both ways without success.

**Comment by dpetka2001** [comment]
I even tried with `vim.schedule` because the blink commands actually schedule the call from `windows.autocompletion.something.accept` and return `true`, but that didn't work either.

**Comment by dpetka2001** [comment]
There was a new update to `blink.compat` and `codeium.nvim` is compatible now. I managed to get a basic PR together, since I couldn't manage to make `<Tab>` work as the example in copilot. If you'd like me to submit it, please do let me know. 

I'm not sure which way you want to go with this and there seems to be quite a lot of backlog for you, so I wouldn't want to burden any further if something that involves `blink.compat` is not desirable.

**Comment by 2nthony** [comment]
only for me: I prefer using `tab` to accept the copilot suggestion, it is just like other IDE(editor) behaviour such as vscode.

so maybe a new extra `blink-copilot` (pseudo name):

```lua
{
  { import = "lazyvim.plugins.extras.coding.blink" },
  { import = "lazyvim.plugins.extras.coding.blink-copilot" },
}
```

but if this requires bunch of code to implement then not worth it😅.

**Comment by elu00** [comment]
For what it's worth,I've gotten codeium working more or less satisfactorily with blink on [this configuration](https://github.com/elu00/dotfiles/blob/main/nvim/lua/plugins/cmp.lua) after a couple of the recent blink.compat commits, although as you guys mentioned having suggestions updated after the initial batch of suggestions seems to not work completely.
