### ISSUE TITLE
feature: Allow disabling leap key bindings

### ISSUE THREAD

**Issue by TxHawks** [LazyVim/LazyVim#476]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

I don't use leap at all other than as an API for flit, so the default mappings are pretty useless to me and I'd like to remove them. However, `keys = { "S", false }` doesn't seem to have any effect.

### Describe the solution you'd like

I'd like to be able to remove the default key mappings

### Describe alternatives you've considered

-

**Comment by folke** [comment]
This is not a bug, or enhancement, so please next time post this in the github discussions.

It should be `keys = {{ "S", false }}`, but that won't work since the leap config function does `leap.add_default_mappings(true)`

The easiest way is to do something like this:

```lua
  {
    "ggandor/leap.nvim",
   keys = function() return {} end,
   config = function() end
 }
```

**Comment by TxHawks** [comment]
The missing `{{}}` were a typo, but thanks for pointing it out and for offering a workaround. Will open a discussion next time.

**Comment by paranormal** [comment]
This is a bug and not an enhancement, disabled plugin's functionality should dissipate.

**Comment by paranormal** [comment]
Sorry for the remark without going at length, it seems I've made some misapprehension here.



currently if you disable the mentioned addon (leap.nvim) you still wouldn't be able to use vi standard keybindings, having an error on pressing f/F complaining about the missing addon. Same goes with s/S, but without error.

Watching few issues with the same error I have i replied to this one automatically, guilty sorry. Should I create a proper ticket or is it somehow known and expected behavior
![image_2023-04-26_20-24-53](https://user-images.githubusercontent.com/140182/234654798-19463738-7215-4cab-b098-f28da32f10e6.png)
?

**Comment by paranormal** [comment]
Anyway, who on earth would remap s/S, substitute is so often used command, why would you use cl if you can type just s.
The plugin is cool, but it shatters well thought and appropriate approach used before.

**Comment by paranormal** [comment]
@folke, it turned out to be the the `which-key` issue, disabling the addon remedies the `s|S` keybinding.
