### ISSUE TITLE
options.lua recommendation for terminal shell on Windows for pwsh should be "pwsh.exe" now

### ISSUE THREAD

**Issue by AddictArts** [LazyVim/LazyVim#4805]
Hopefully this helps someone else out there who experiences this issue. I know there are fewer `powershell` `Windows` users. I'd happily be in `zsh` but I don't get that choice.

The recommendation in the options.lua is `LazyVim.terminal.shell("pwsh")` cause errors on exit from neovim saving the session.

It now should be `LazyVim.terminal.shell("pwsh.exe")` at least from my testing. Users may also need to delete old sessions.

https://github.com/LazyVim/LazyVim/blob/bb289f4345835d98df7d0dfd4a26fd0dffa7e89a/lua/lazyvim/config/options.lua#L29

See this issue for the errors

https://github.com/LazyVim/LazyVim/issues/4784

Resolution:
After clearing the sessions and changing to `pwsh.exe` my sessions are persisting.

**Comment by AddictArts** [comment]
> I just changed the shellcmdline flags to match exactly what's in the NEovim docs, however, I'm pretty sure the previous settings also worked fine.
> 
> Your `fix` doesn't actually setup powershell, so that is completely wrong.
> 
> I suspect you have an issue somewhere in your `powershell.ps1` file.

I'd like to believe this be true, however, I have tried across 2 different Windows 11 installations. Two different versions of Windows 11. Same issue happens. Also, it used to work until recent releases of LazyVim, like within the last 2 months. Something has changed and the fix I suggest above resolves it for me. If you are not running WIndows 11 and testing there, anyone commenting on this issue, you are guessing.

**Comment by folke** [comment]
Check the neovim help docs for yourself. I'm also perfectly fine using it on windows

**Comment by RC5K** [comment]
Hi all, I encountered this issue as well and wanted to share my findings. From my testing, it seems that the issue is caused by having configurations related to PSReadLine in the Powershell profile.

Since removing the PSReadLine configurations isn't an option for me, I copied the `vim.o.shellcmdflag` string from `LazyVim.terminal.setup()` to my options.lua and added `-NoProfile` to the `vim.o.shellcmdflag` string.

Like so:
```lua
LazyVim.terminal.setup("pwsh")
vim.o.shellcmdflag =
		"-NoProfile -NoLogo -NonInteractive -ExecutionPolicy RemoteSigned -Command [Console]::InputEncoding=[Console]::OutputEncoding=[System.Text.UTF8Encoding]::new();$PSDefaultParameterValues['Out-File:Encoding']='utf8';$PSStyle.OutputRendering='plaintext';Remove-Alias -Force -ErrorAction SilentlyContinue tee;"
```

Hope this helps.

**Comment by AddictArts** [comment]
Yes I am using PSReadLine, weird that `.exe` fixes it. Thanks for the info and testing @RC5K, great work and much appreciated.

**Comment by AK47are** [comment]
hi @AddictArts, although it might be late to explain, the fix of "pwsh.exe" is not weird. This is because LazyVim.terminal.setup() only applies config when it matches `pwsh` or `powershell` string, and its config for `vim.o.shellcmdflag` causes the issue. Here is the [code](https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/util/terminal.lua), you can verify this by running `:lua print(vim.o.shellcmdflag)`.

I experienced a similar [issue](https://github.com/folke/persistence.nvim/issues/110) (though with different symptoms), and I believe it shares the same culprit. Besides persistence.nvim hanging, I also experience a hang when using :!, which is also caused by configurations related to PSReadLine

For example, in the image below, I only set the same [terminal configuration](https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/util/terminal.lua) as LazyVim. It initially pops up an error, continues to run, but eventually hangs.

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/37b7b9ba-5b48-4cd7-8e50-da3ca70ad33c" />

I'm not sure if others can reproduce this. My [pwsh config](https://github.com/AK47are/dotfiles/blob/windows/Documents/PowerShell/Microsoft.PowerShell_profile.ps1) is linked here.

I have now found four different situations of this bug: hanging before entering a session, hanging before quitting nvim, `:!` hanging, and a fleeting error upon quitting nvim.I think LazyVim should add the `-NoProfile` parameter to `vim.o.shellcmdflag`. This would prevent these strange and annoying errors without negatively impacting other users' experience. What do you think, @folke?

**Comment by folke** [comment]
Sure, feel free to add a PR, but then some users will probably complain since they rely on some things in their profile.
But yes, might fix more issues than introduce new ones, no idea.

I'm on Linux, so not really a problem for me
