### ISSUE TITLE
bug: `<leader>ss` failing to open telescope symbol select on `.ts` files

### ISSUE THREAD

**Issue by kryptonian41** [LazyVim/LazyVim#4959]
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.2

### Operating system/version

MacOS 15.2
Typescript extra has been enabled to configure LSP.

### Describe the bug

I am using the bare-bones LazyVim config, only extras like JSON, markdown, toml, and typescript are enabled additionally.

Bizarre behavior from both telescope.nvim and trouble.nvim. Running `<leader>ss` fails to return a list of symbols when running on `.ts` files, while its running fine for the `.tsx` files in the same monorepo. Similar behavior is displayed by `<leader>cs`.

What flips me off is that running `:Telescope lsp_document_symbols` works on `.ts` files as well. 

### Error on .ts file (`<leader>ss`)
![Image](https://github.com/user-attachments/assets/f62c15f8-756c-4646-84e7-e5a1b4753ea4)

### Works fine on .tsx file (`<leader>ss`)
![Image](https://github.com/user-attachments/assets/100cb6c5-74a4-45bc-b8b9-31486b7c4b42)

### Error from Trouble on .ts file
![Image](https://github.com/user-attachments/assets/d3da9584-46d8-454d-ab96-db6d6e2dd7e2)

### Telescope after running `:Telescope lsp_document_symbols` on a `.ts` file
![Image](https://github.com/user-attachments/assets/9979293e-2f4b-4e02-9184-e8a912eac696)

### Steps To Reproduce

1. Open a .ts file
2. Press `<leader>ss`

### Expected Behavior

Should open the telescope buffer with a list of symbols to choose from when running `<leader>ss` on `.ts` files, if the the typescript extra is enabled and LSP is configured properly. Currently throws an error.

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- add any other plugins here
  },
})
```

**Comment by folke** [comment]
Did you change the LazyVim kind filters?

**Comment by dpetka2001** [comment]
@folke With `lua_ls` when I do `lua require("telescope.builtin").lsp_document_symbols({symbols = {"Class"}})` then I get a warning `[telescope.builtin.lsp_document_symbols]: No results from textDocument/documentSymbol` which comes from [here](https://github.com/nvim-telescope/telescope.nvim/blob/2eca9ba22002184ac05eddbe47a7fe2d5a384dfc/lua/telescope/builtin/__lsp.lua#L356). But with `vtsls` if I do the same in a TS file like the example in the OP, then I get warning `[telescope.filter_symbols]: class symbol(s) were not part of the query results` which comes from [here](https://github.com/nvim-telescope/telescope.nvim/blob/2eca9ba22002184ac05eddbe47a7fe2d5a384dfc/lua/telescope/utils.lua#L173). So, with `lua_ls` the result is empty from the server from the beginning and returns early, whereas with `vtsls` it seems that something is returned and then [this line](https://github.com/nvim-telescope/telescope.nvim/blob/2eca9ba22002184ac05eddbe47a7fe2d5a384dfc/lua/telescope/builtin/__lsp.lua#L363) further filters symbols and maybe returns `nil` somehow that causes `vim.tbl_isempty()` to error?

Can't quite understand in more detail myself unfortunately.

**Comment by folke** [comment]
ok, thank you for investigating. should be reported in telescope

**Comment by dpetka2001** [comment]
Also this error started happening after commit https://github.com/nvim-telescope/telescope.nvim/commit/85922dde3767e01d42a08e750a773effbffaea3e whereas the previous commit https://github.com/nvim-telescope/telescope.nvim/commit/f06e7a887185796e0d37088237572f8ce03a1553 doesn't show this error. The symbols not showing as OP wants is just because of the stripped down default symbols LazyVim uses. He could add `Variable` to them or just change the mapping to call `Telescope lsp_document_symbols` without defining any `symbols` which should return all of them. 

But the error seems to come from Telescope itself. Hope I didn't make any mistake and rushed to conclusions.

**Comment by folke** [comment]
You're right:
![Image](https://github.com/user-attachments/assets/2807be6b-c704-45e9-a900-948642e3fb2a)

**Comment by dpetka2001** [comment]
Yeah I cloned Telescope and added 2 prints before [this line](https://github.com/nvim-telescope/telescope.nvim/blob/2eca9ba22002184ac05eddbe47a7fe2d5a384dfc/lua/telescope/builtin/__lsp.lua#L363). And before that line `locations` is a table but after `utils.filter_symbols` is applied then `locations = nil`. So, something going on in that function.

**Comment by kryptonian41** [comment]
@folke Trouble has the same issue where for `.ts` files `<leader>cs` shows `No results for symbols`.

**Comment by folke** [comment]
@kryptonian41 trouble works perfectly fine. There's no symbols, since we're filtering out a lot of symbol kinds.

**Comment by dpetka2001** [comment]
@kryptonian41 You should also report it at Telescope repo, so it gets resolved, otherwise will you stay in a previous commit for ever?

As for Trouble, this happens because Trouble by default doesn't show all symbols by default as you can see in the [docs](https://github.com/folke/trouble.nvim#%EF%B8%8F-configuration) (search for `modes.symbols.filter.kind` and you'll see what it shows by default). Alternatively you can call `Trouble lsp_document_symbols toggle` to show more symbols if you'd like or change in the Trouble plugin spec `modes.symbols.filter.kind` and add more symbols to your liking (but because that is a list you would have to copy over the default ones as well except if you're fine with just defining your own).

**Comment by dpetka2001** [comment]
So, I mentioned in my [first comment](https://github.com/LazyVim/LazyVim/issues/4959#issuecomment-2521389026) that I was getting the warning `[telescope.filter_symbols]: class symbol(s) were not part of the query results`, which meant that we had at least reached the point [here in this function](https://github.com/nvim-telescope/telescope.nvim/blob/2eca9ba22002184ac05eddbe47a7fe2d5a384dfc/lua/telescope/utils.lua#L170-L175). 

And I kept thinking about why `locations = nil` just after the `utils.filter_symbols` function. I think it's because after these warnings the function doesn't return anything. And I tried in my local forked Telescope repo and added just a `return {}` after the 2 [if-elseif warnings here](https://github.com/nvim-telescope/telescope.nvim/blob/2eca9ba22002184ac05eddbe47a7fe2d5a384dfc/lua/telescope/utils.lua#L170-L182) and it seems to work. I don't get the error about `vim.tbl_isempty expected table but got nil`. So, between current lines 182 and 183 just add `return {}`.

@kryptonian41 Maybe you would like to mention that in an issue at Telescope repo. I'm not that familiar with Telescope codebase and not 100% sure if the above addition has potentially other side-effects. But the thing is that if we get to the end of that function it seems to implicitly return `nil` because it doesn't have a statement to return something explicitly. I'm sure the people over at Telescope repo will know better than me if you explain things to them, like I've already mentioned as well.
