### ISSUE TITLE
Duplicate `<leader>sh` keymap

### ISSUE THREAD

**Issue by mdoury** [LazyVim/LazyVim#50]
Currently the `<leader>sh` keymap is used for the two following commands:
- `Telescope highlights`
- `Telescope help_tags`

Therefore the [first](https://github.com/LazyVim/LazyVim/blob/46dba8f67e96cb8aa5496351696b11b49093ecc8/lua/lazyvim/plugins/editor.lua#L66)  is overwritten by the [latter](https://github.com/LazyVim/LazyVim/blob/46dba8f67e96cb8aa5496351696b11b49093ecc8/lua/lazyvim/plugins/editor.lua#L73).

**Comment by lkhphuc** [comment]
The telescope keymaps are a bit messy at the moment.
Here are my recommended mappings:
```
  keys = {
    -- Enhanced version of "/" search command
    { "<leader>/", builtin.current_buffer_fuzzy_find, desc = "Fuzzy search in buffer" },   
    { "<leader>s/", builtin.search_history, desc = "Search history" },
  
  -- Enhanced version of "*"
    { "<leader>*", builtin.grep_string, desc = "Search word under cursor" },

    { "<leader>sb", builtin.buffers, desc = "Buffers" },
    { "<leader>so", builtin.oldfiles, desc = "Recent [O]ld files" },
    { "<leader>sf", builtin.find_files, desc = "Files" },
    { "<leader>sF", "<Cmd>Telescope file_browser<CR>", desc = "Browse files" },

    { "<leader>sG", util.telescope("live_grep", { cwd = false }), desc = "Grep (cwd)" },
    { "<leader>sg", util.telescope("live_grep"), desc = "Grep (root dir)" },
    -- By starting grep_string with empty search key, we fuzzy over everything 
    { "<leader>st", "<cmd>Telescope grep_string search= theme=ivy <CR>", desc = "Fuzzy search workspace" },
     -- sH, sM to search help and manpage would be more "consistent", but I search help more often than highlight, so lowercase is reserved for that
    { "<leader>sh", "<cmd>Telescope help_tags<cr>", desc = "Help Pages" },
    { "<leader>sH", "<cmd>Telescope highlights<cr>", desc = "Search Highlight Groups" },
    { "<leader>sM", builtin.man_pages, desc = "[M]an Page" },

    -- Since ; and : is the same button to start command
    { "<leader>s;", "<cmd>Telescope commands<cr>", desc = "Commands" },
    { "<leader>sc", builtin.command_history, desc = "Command history" },

    -- since register start with tick already 
    { "<leader>s'", builtin.registers, desc = "Registers" },
    { "<leader>sk", builtin.keymaps, desc = "Keymaps" },
    { "<leader>sj", builtin.jumplist, desc = "Jumplist" },
    { "<leader>sm", builtin.marks, desc = "Marks" },
    { "<leader>sr", builtin.resume, desc = "Resume last search" },
    { "<leader>sp", builtin.builtin, desc = "Pickers" },

    { "<leader>sP", builtin.projects, desc = "Projects" },
    { "<leader>sO", builtin.vim_options, desc = "Vim options" },
    { "<leader>s<Tab>", "<Cmd>Telescope telescope-tabs list_tabs<CR>", desc = "Tabs" },

    { "<leader>gc", "<cmd>Telescope git_commits<CR>", desc = "commits" },
    { "<leader>gs", "<cmd>Telescope git_status<CR>", desc = "status" },
    { "<leader>sa", "<cmd>Telescope autocommands<cr>", desc = "Auto Commands" },
    {
      "<leader>ss",
      util.telescope("lsp_document_symbols", {
        symbols = {
          "Class",
          "Function",
          "Method",
          "Constructor",
          "Interface",
          "Module",
          "Struct",
          "Trait",
          "Field",
          "Property",
        },
      }),
      desc = "Goto Symbol",
    },
```


By the way, is there any way to completely override the `keys` provided in LazyVim? cc @folke

**Comment by folke** [comment]
@lkhphuc yes, anywhere in tables like `opts` or `keys`, you can specify `__merge = false`.

So `keys = {__merge = false, {"<leader>f"}}` would not merge with parent spec and add a single key.

In an opts table, you can use `__merge=false` to prevent some keys (can be nested) to merge or you can add `__merge = true` to lists to extend a list instead of replacing it.

You can also set a key to `vim.NIL` to have it be cleared and set to `nil` after merge.

So merging works similarly to `vim.tbl_deep_extend`, but you can override the merging strategy for any nested value with `__merge`.

Still need to document this though and obvioulsy is for advanced usage. Not that beginner friendly :)

**Comment by folke** [comment]
I think I will change that merging strategy syntax.

Maybe it makes more sense, that we can specify something like:

```lua
return {
  -- base spec specifies that ensure_installed can be merged
  {
    "nvim-treesitter/nvim-treesitter",
    opts = {
      ensure_installed = {
        "bash",
        "help",
        "html",
      },
    },
    merge = {
      ["opts"] = true,
      ["opts.ensure_installed"] = true,
    },
  },

  -- add typescript. Will be added to base ensure_installed
  {
    "nvim-treesitter/nvim-treesitter",
    opts = {
      ensure_installed = {
        "typescript",
        "tsx",
      },
    },
  },

  -- add telescope, but dont use the default keys
  {
    "nvim-telescope/telescope.nvim",
    merge = {
      keys = false,
    },
    keys = {
      { "<leader>,", "<cmd>Telescope buffers show_all_buffers=true<cr>", desc = "Switch Buffer" },
      { "<leader>/", util.telescope("live_grep"), desc = "Find in Files (Grep)" },
    },
  },
}
```

Wdyt?
```

**Comment by lkhphuc** [comment]
Thank @folke . I prefer the current method, which is merge by default, and toggle with a special `__merge=false`. I think it's less verbose, just need to be documented somewhere. 

After all the reason I use LazyVim is because I'm lazy and want to merge my config with LazyVim with best practices, keymaps and up-to-date configs. 
The case I would not want to merge is very rare (like telescope), otherwise I would just copy and paste from LazyVim instead of specify it as a spec.

**Comment by folke** [comment]
Scrap everything I said :)

The current `__merge=false` and what I proposed (`merge=...`) are both too complicated, so I'll do it differently.

I'll just make it so `keys=` or any of the other handlers can behave the same as `opt=`, meaning that it can also be a `function`, where the user can then return a new list of keys instead of default behavior of merging.

That nested merging is not needed that way.

So your example for telescope would then become:

```lua
  -- add telescope, but dont use the default keys
  {
    "nvim-telescope/telescope.nvim",
    keys = function()
      return {
        { "<leader>,", "<cmd>Telescope buffers show_all_buffers=true<cr>", desc = "Switch Buffer" },
        { "<leader>/", util.telescope("live_grep"), desc = "Find in Files (Grep)" },
      }
    end,
  },
```

Wouldn't this make more sense?

**Comment by lkhphuc** [comment]
Yes it is. Looking forward to use that.

**Comment by folke** [comment]
The new functionality is now live, so keys can be a function that returns a new list of keys to use instead.

Make sure to update `lazy.nvim` first.
