### ISSUE TITLE
bug: Failed to download prebuilt_binaries of blink after changing the config.

### ISSUE THREAD

**Issue by road2coder** [LazyVim/LazyVim#5253]
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.2

### Operating system/version

MacOS 15.2 and archlinux

### Describe the bug

The following error occurs on both macos 15.2 and the latest archlinux when using the minimal lazyvim with only the `blink` config changed.
```
   Error  16:28:15 notify.error ...vim/lazy/blink.cmp/lua/blink/cmp/fuzzy/download/init.lua:27: 
Detected an out of date or missing fuzzy matching library. Can't download from github due to not being on a git tag and no `fuzzy.prebuilt_binaries.force_version` is set.
Either run `cargo build --release` via your package manager, switch to a git tag, or set `fuzzy.prebuilt_binaries.force_version` in config. See the docs for more info.
```

### Steps To Reproduce

1. clone the starter: `git clone https://github.com/LazyVim/starter ~/.config/lazyvim-test`
2. change the config related to `blink`:
```lua
{
  "saghen/blink.cmp",
  ---@module 'blink.cmp'
  ---@type blink.cmp.Config
  opts = {
    keymap = {
      preset = "default",
    },
  },
},
```
3. run neovim with the config: `NVIM_APPNAME="lazyvim-test" nvim`
4. open any buffer

### Expected Behavior

download prebuilt_binaries successfully

### Repro

```lua

```

**Comment by dpetka2001** [comment]
That's normal. `lazy.nvim` by default downloads the latest HEAD  of blink (because of the plugin spec in your personal configuration). If you open the Lazy UI, you should have an update for blink. Just update blink and you won't see the error. Or put `vim.g.lazyvim_blink_main = true` in your `options.lua` file if you want to be on blink main branch.

**Comment by road2coder** [comment]
> That's normal. `lazy.nvim` by default downloads the latest HEAD of blink (because of the plugin spec in your personal configuration). If you open the Lazy UI, you should have an update for blink. Just update blink and you won't see the error. Or put `vim.g.lazyvim_blink_main = true` in your `options.lua` file if you want to be on blink main branch.

Works, thank you. But why it also works if I delete the following config?
```lua
{
  "saghen/blink.cmp",
  ---@module 'blink.cmp'
  ---@type blink.cmp.Config
  opts = {
    keymap = {
      preset = "default",
    },
  },
},
```

**Comment by dpetka2001** [comment]
Because by default Lazyvim sets blink to `version = *` (which means the latest stable). If there are valid plugin specs in your personal configuration then they will get installed as is, but because Lazyvim hasn't finished installing yet, the specs arent't merged until after Lazyvim has finished installing. That's why after Lazyvim finished installing you'll also see the blink update in the Lazy UI.

**Comment by road2coder** [comment]
> Because by default Lazyvim sets blink to `version = *` (which means the latest stable). If there are valid plugin specs in your personal configuration then they will get installed as is, but because Lazyvim hasn't finished installing yet, the specs arent't merged until after Lazyvim has finished installing. That's why after Lazyvim finished installing you'll also see the blink update in the Lazy UI.

It's a little bit different to my understanding. Anyway, it works ok now. I'll read the doc more carefully later.
