### ISSUE TITLE
bug: hover popup is stuck on the screen

### ISSUE THREAD

**Issue by zaynOm** [LazyVim/LazyVim#5256]
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.2

### Operating system/version

Archlinux

### Describe the bug

while typing a popup is drawn and I can't get rid of it

![Image](https://github.com/user-attachments/assets/7b031521-9676-45fd-8daa-6f760b896ad4)

### Steps To Reproduce

just typing

### Expected Behavior

no popup to show

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- add any other plugins here
  },
})
```

**Comment by dpetka2001** [comment]
Can you reproduce it with the minimal repro? Because I can't.

**Comment by zaynOm** [comment]
I tried for a short time and it didn't, the bug is weird cuz it randomly occur I still can't identify the reason

**Comment by dpetka2001** [comment]
Well you should first identify the reason, because this is not reproducible with minimal repro. Or at least provide appropriate reproducible steps where one can verify this happens.

**Comment by zaynOm** [comment]
I got it on the repro.

```lua
   Error  01:37:01 PM notify.error blink.cmp ...ta/nvim/lazy/blink.cmp/lua/blink/cmp/lib/window/init.lua:101: Keyboard interrupt
   Error  01:31:15 PM notify.error Snacks Terminal exited with code 1.
Check for any errors.
```

![Image](https://github.com/user-attachments/assets/0c79a163-06ed-4e3c-8e32-e2e2da814e0e)

**Comment by dpetka2001** [comment]
This error comes from blink though. You should report it there. Are you using `<C-c>` by any chance when this happens?

**Comment by zaynOm** [comment]
yes it always appears after clicking `<C-c>`

**Comment by dpetka2001** [comment]
You shouldn't be using `<C-c>`. See [comment here from Neovim core maintainer](https://github.com/LazyVim/LazyVim/issues/5256#issuecomment-2562948497). Or use it at your own risk. It doesn't trigger the `InsertLeave` event and seems to be skipping some other stuff as well (although not sure what it skips since I'm not a Neovim maintainer and not familiar with Neovim internals). This isn't a LazyVim bug.

**Comment by zaynOm** [comment]
but the thing is I have `<C-c>` mapped to to `<Esc>`
```lua
map({ "i", "n" }, "<C-c>", "<cmd>noh<cr><esc>", { desc = "Escape and Clear hlsearch" })
```

**Comment by dpetka2001** [comment]
Try also mapping it in terminal mode, because i see `Snacks.terminal` in the error. Either way `<C-c>` has unpredictable behavior in Neovim and you're responsible for using it. Neovim devs have admitted it themselves and users are discouraged from using it unless they know what they're doing. Not a Lazyvim bug however you decide to look at it.

**Comment by zaynOm** [comment]
thx, i appreciate your help
