### ISSUE TITLE
bug: Neotree does not open in root dir of a git repository on Windows

### ISSUE THREAD

**Issue by 7erra** [LazyVim/LazyVim#561]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.0-dev-1051+g1d8b77da6

### Operating system/version

Windows 11

### Describe the bug

When using the keyboard shortcut `<leader>e` NeoTree only shows the current path with forward slashes instead of the folder's content on Windows. The directory must be a git repository.

### Steps To Reproduce

1. Create a new folder
2. Execute `nvim .`
3. Create new file
4. Press `<leader>e`
At this point the content is shown correctly
5. Exit nvim
6. Run `git init`
7. Execute `nvim .`
8. Press `<leader>e` twice (close and open again)
No content is shown

### Expected Behavior

Folder content should be displayed just like when the folder is not a git repository.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by dpetka2001** [comment]
Is it saying perhaps that there are hidden items? Does `H` toggle the hidden files for you?

**Comment by 7erra** [comment]
H does toggle hidden files but the issue persists

**Comment by dpetka2001** [comment]
Unfortunately I'm not on Windows and cannot confirm the issue you're describing. I don't have such issue myself on Linux Mint 21.1 (neo-tree opens correctly in a git repo). Can you install Lazyvim in a VM and test if the issue persists with vanilla Neovim instead of Lazyvim. If it works with vanilla Neovim then it's a problem with Lazyvim, if it doesn't work with vanilla Neovim either then it's likely a neo-tree problem.

**Comment by 7erra** [comment]
I don't have enough knowledge to set up a VM and test what you describe. I am also running Manjaro where this issue does not occur.

**Comment by dpetka2001** [comment]
On manjaro do you also use Lazyvim or vanilla Neovim? Since this issue happens only on windows, I can think of 2 possibilities. Either Lavyvim get_root() fails to discover root_dir on windows or this is a problem of neo-tree on windows. You should also create an issue on neo-tree repo, maybe someone has encountered a similar problem on windows.

**Comment by 7erra** [comment]
>  Lazyvim or vanilla Neovim?

Lazyvim

> You should also create an issue on neo-tree repo

Will do

**Comment by folke** [comment]
Files paths using forward slashes are valid on Windows, so this is likely a neotree issue
