### ISSUE TITLE
bug: (Telescope:live_grep) ripgrep consumes all ram and crashes neovim

### ISSUE THREAD

**Issue by peter-lejon-v** [LazyVim/LazyVim#580]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.0

### Operating system/version

Linux 6.2.10-1

### Describe the bug

When doing a live_grep on a decent sized project. ripgrep consumes all available memory.

### Steps To Reproduce

<leader>sg in a fairly large project

### Expected Behavior

not crashing

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/LazyVim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by VinukaThejana** [comment]
I too have this issue. Telescope works fine when finding files and ripgrep too works outside of neovim but when I try to live grep inside neovim it freezes

**Comment by dpetka2001** [comment]
Like I said have you tried it with vanilla Neovim and Telescope? If the problem persists there (which I guess it should since I don't think Lazyvim alters Telescope) then it's not Lazyvim's problem. It's a problem with Telescope and how it incorporates ripgrep for live grepping. So it should be more appropriate to raise an issue in Telescope's repo if that's the case.

**Comment by folke** [comment]
not a lazyvim issue

**Comment by peter-lejon-v** [comment]
It works for me with vanilla setup but not lazy

**Comment by theimerj** [comment]
I also experienced this issue. This happens when ripgrep encounters some huge files like huge logs, long minified javascript, lock files and so on.

I was able to mitigate the issue with  better ignore files.

You can use `.rgignore` and `.ignore` files to extend your ignore list without affecting your `.gitignore`. You can read more [here](https://github.com/BurntSushi/ripgrep/blob/master/GUIDE.md#configuration-file).

I also recommend setting up a global [ripgrep config file](https://github.com/BurntSushi/ripgrep/blob/master/GUIDE.md#configuration-file).

I also encountered situations when ripgrep was taking 30GB+ of RAM. When I tested it in terminal everything was smooth and extremely fast. 

However, with the new ignore files it does not happen anymore.
