### ISSUE TITLE
feature: Would this project consider integreting any Multiple cursors plugin? 

### ISSUE THREAD

**Issue by you-n-g** [LazyVim/LazyVim#695]
### Did you check the docs?

- [X] I have read all the LazyVim docs

### Is your feature request related to a problem? Please describe.

Would this project consider integreting any Multiple cursors plugin like https://github.com/mg979/vim-visual-multi ? 

### Describe the solution you'd like

A multiple cursors plugin is provided and configured.
The keymaping conflictions are resolved.

### Describe alternatives you've considered

NA

**Comment by folke** [comment]
Not for everyone, but you can of course add it to your own onfig

**Comment by azzamsa** [comment]
@folke Coming from Emacs, I rely heavily on multiple cursors to change some strings in the current buffer. I am curious about whether to add `vim-visual-multi` to my config because I see LazyVim as a 'complete' solution. So, I assume you have a better workflow to change multiple strings at once? In my opinion, nvim-spectre is overkill for a single-buffer small region replacement.

**Comment by azzamsa** [comment]
Based on this config https://github.com/folke/dot/blob/1007fc65738ad1f7a3e9c91432430017a6878378/nvim/lua/plugins/tmp.lua#L55C6-L55C23, I believe Folke is using muren.nvim

**Comment by g-h-97** [comment]
Hi @folke ,

Not to be rude, but @azzamsa is right. If this is a neovim distro (a lazy one :) ), it should contain a plugin such as `vim-visual-multi` at least in the extras with its respective keybindings in the `which-key` plugin.

Kindly consider this,
Thanks,
Regards,

**Comment by dpetka2001** [comment]
I only have the following 
```lua
  {
    "mg979/vim-visual-multi",
    event = "LazyFile",
    init = function()
      vim.g.VM_theme = "purplegray"
      vim.g.VM_mouse_mappings = 1
    end,
  },
```
and it works pretty well. I admit I don't use it that much, so I can't speak to all of its features. I mainly do `<C-n>` to start selecting the current word and subsequent instances of the same word or I just do `<C-Down>` for vertical cursors or just `<C-Mouse1>` to select different not sequential points where I want the cursors to appear. 

>  If this is a neovim distro (a lazy one :) ), it should contain a plugin such as vim-visual-multi at least in the extras with its respective keybindings in the which-key plugin.

I personally, as just a simple user like you, don't agree with this. A Neovim distro only has to give the users sane defaults. Since Neovim itself doesn't support multiple cursors, this is extra effort and maintenance for something that is not officially supported. So, this belongs in the user's personal configuration in my humble opinion. 

There's also a Lua alternative https://github.com/jake-stewart/multicursor.nvim, which I've tried briefly but didn't like the fact that it didn't show all the cursors update simultaneously. However, it might have other different features that might fit someone else's personal preferences, so you should try it out yourself and decide which one fits you best.

**Comment by g-h-97** [comment]
Hi @dpetka2001 ,

It seems that it was an issue on my end; after correction the plugin works perfectly fine.

I fully understand, however, I think the `vim-visual-multi` is a popular plugin that is used by thousands of developers worldwide and I personally can't think of coding (or text editing in general for that matter) without the ability to edit multiple lines, words...etc when needed,

I genuinely think this functionality should be part of any text editor or IDE, and it actually is part of most of them. TBH this doesn't really affect me or you that much, since we can always customise our setups to our needs fairly easily; but it's so convenient and great to have such plugins at a press of a button, more so for the casual user,

**Comment by dpetka2001** [comment]
That's why the personal configuration exists. Not everything can be defaults in a distro. Ans it just takes 4 lines of a plugin spec to install and use it. Don't take me wrong, i also have it installed (though i'm not that accustomed to fully using it), but in the end it's the maintainer's decision and i can understand perfectly if he thinks it would be better for users to install it themselves. He's already made his decision on this topic.

**Comment by azzamsa** [comment]
I am using this.

```lua
    {
        "smoka7/multicursors.nvim",
        event = "VeryLazy",
        dependencies = {
            "smoka7/hydra.nvim",
        },
        opts = {},
        cmd = { "MCstart", "MCvisual", "MCclear", "MCpattern", "MCvisualPattern", "MCunderCursor" },
        config = function()
            require("multicursors").setup({
                -- Any hint position has the potential to cover the target text.
                -- hint_config = false,
                hint_config = {
                    border = "single",
                    position = "top-left",
                    type = "statusline",
                },
                generate_hints = {
                    normal = true,
                    insert = true,
                    extend = true,
                    config = {
                        -- Enable these line if you use `type = window`
                        -- column_count = 2,
                        -- max_hint_length = 15,
                    },
                },
            })
        end,
    },
```
