### ISSUE TITLE
usage: Unclear how to unset lspconfig keybinding

### ISSUE THREAD

**Issue by JJGO** [LazyVim/LazyVim#93]
First, thanks for developing and publishing this, it's really great as a starting point for neovim.

I was checking the `plugins/example.lua` trying to check how to unset premade keybindings by LazyVim. In particular, I want to use the `K` keymap in normal mode for moving this around with mini.move. I'm doing this by adding the following to my `init.lua`

```lua
require("mini.move").setup({
  mappings = {
    left = "H",
    right = "L",
    down = "J",
    up = "K",
    line_left = "H",
    line_right = "L",
    line_down = "J",
    line_up = "K",
  },
})
```

However, the `on_attach` call by lspconfig that LazyVim preconfigures in [keymaps.lua](https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/plugins/lsp/keymaps.lua#L13) takes precendence so `K` doesn't call the mini.move function.

As a sanity check

```
:nmap K
n  K           *@<Lua 807: /usr/local/Cellar/neovim/0.8.1/share/nvim/runtime/lua/vim/lsp/buf.lua:41>
                 Hover
n  K           * <Cmd>lua MiniMove.move_line('up')<CR>
                 Move line up
```

What is the intended way of disabling particular keybindings done vim LazyVim in this way?

**Comment by al-ce** [comment]
Don't know if this is the most efficient way but I copied the entire [plugins/lsp/init.lua](https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/plugins/lsp/init.lua) file in my `plugins/` folder (I did `plugins/lsp.lua` where I put some other lsp related plugin configs) because there were some other things I wanted to change. Relevant changes below:

```lua
  {
    "neovim/nvim-lspconfig",
    -- other relevant lazy.nvim settings here, including opts table
    config = function(plugin, opts)
      -- other config stuff here

      -- setup formatting and keymaps
      require("lazyvim.util").on_attach(function(client, buffer)
        require("lazyvim.plugins.lsp.format").on_attach(client, buffer)
        -- require("lazyvim.plugins.lsp.keymaps").on_attach(client, buffer)
        require("config.lsp_keymaps").on_attach(client, buffer)
      end)

    -- Other config stuff here
    })
    end
  }
```

This just overrides the `on_attach` call for keymaps I think you're referring to, while keeping the `format` opts. The I add a call to `config/lsp_keymaps.lua` (where the optional `keymaps.lua`/`options.lua` etc files are in the runtime path) that just has a copy of [plugins/lsp/keymaps.lua](https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/plugins/lsp/keymaps.lua), and from there I can comment out/edit whatever.

Again, not sure that's the most efficient way, but I like it since I can update to any other changes I want to follow with little hassle, since lazy.nvim makes updates so easy to follow.

**Comment by folke** [comment]
I'll see for an easier way to override those mapping tomorrow!

**Comment by folke** [comment]
I just pushed some change to make it easier to delete/add/change lsp keymaps:

```lua
  {
    "neovim/nvim-lspconfig",
    init = function()
      local keys = require("lazyvim.plugins.lsp.keymaps").get()
      -- change a keymap
      keys[#keys + 1] = { "K", "<cmd>echo 'hello'<cr>" }
      -- disable a keymap
      keys[#keys + 1] = { "K", false }
      -- add a keymap
      keys[#keys + 1] = { "H", "<cmd>echo 'hello'<cr>" }
    end,
}
```

The keymap definition is the same as for the `lazy.nvim` `keys` property
